// DAORAE KOREAN BBQ - BUKIT INDAH OUTLET
// Trilingual Menu Database File (Korean, English, Chinese)
// Updated prices matching official Bukit Indah menu.pdf

const MENU_ITEMS = [
    {
        id: "set-1",
        category: "set",
        nameKo: "SET1",
        nameEn: "3~4 pax",
        nameZh: "3~4 pax",
        price: "RM 248.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 돼지갈비, 고추장 삼겹살, 김치전골, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Pork Ribs, Chili Sauce Pork Belly, Kimchi Hot Pot, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、排骨、辣酱五花肉、泡菜火锅、蔬菜煎饼",
        image: "assets/menu/set1.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-2",
        category: "set",
        nameKo: "SET2",
        nameEn: "3~4 pax",
        nameZh: "3~4 pax",
        price: "RM 248.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 양념닭갈비, 양념쭈꾸미, 김치전골, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Marinated Chicken, Marinated Spicy Webfoot Octopus, Kimchi Hot Pot, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、调味鸡肉、调味小八爪鱼、泡菜火锅、蔬菜煎饼",
        image: "assets/menu/set2.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-3",
        category: "set",
        nameKo: "SET3",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 김치찌개, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Kimchi Soup, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set3.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-4",
        category: "set",
        nameKo: "SET4",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "항정살, 돼지갈비, 돼지 주물럭, 김치찌개, 부추전",
        descEn: "Pork Jowls, Pork Ribs, Marinated Pork Special, Kimchi Soup, Chive Pancake",
        descZh: "猪面颊肉、猪排骨、调味特选猪肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set4.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-5",
        category: "set",
        nameKo: "SET5",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "돼지 스페셜, 돼지갈비, 닭갈비, 김치찌개, 부추전",
        descEn: "Pork Special, Pork Ribs, Marinated Chicken, Kimchi Soup, Chive Pancake",
        descZh: "猪肉特选、猪排骨、调味鸡肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set5.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-6",
        category: "set",
        nameKo: "SET6",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 148.00",
        descKo: "돼지갈비, 매운 닭갈비, 양념쭈꾸미, 김치찌개, 부추전",
        descEn: "Pork Ribs, Spicy Chicken, Spicy Baby Octopus, Kimchi Soup, Chive Pancake",
        descZh: "猪排骨、辣味鸡肉、辣味小八爪鱼、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set6.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 2
    },
    {
        id: "beef-7",
        category: "beef",
        nameKo: "B01. 갈비본살",
        nameEn: "Galbi Bonsal",
        nameZh: "GALBI BONSAL",
        price: "RM 130.00",
        descKo: "양념하지 않은 신선한 갈비본살 숯불구이 (갈비뼈를 제거한 소갈비살)",
        descEn: "Fresh boneless short rib without marinade, charcoal grilled",
        descZh: "无调味新鲜去骨牛小排，炭火烤制",
        image: "assets/menu/galbi_bonsal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-8",
        category: "beef",
        nameKo: "B02. 생갈비",
        nameEn: "Saeng Galbi",
        nameZh: "SAENG GALBI",
        price: "RM 130.00",
        descKo: "양념하지 않고 칼집을 내어 구운 전통 생 소갈비구이",
        descEn: "Beef short ribs butterflied or accordion cut, without marinade and char-grilled.",
        descZh: "蝴蝶切或风琴切的无调味小牛排，炭火烤制",
        image: "assets/menu/saeng_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-9",
        category: "beef",
        nameKo: "B03. 왕갈비",
        nameEn: "Wang Galbi",
        nameZh: "WANG GALBI",
        price: "RM 130.00",
        descKo: "다오래 한방 특제 간장 양념장에 재워 맛을 낸 손질 소왕갈비",
        descEn: "Beef short rib specially hand filleted marinated with special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的特选纯手工牛小排",
        image: "assets/menu/wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-10",
        category: "beef",
        nameKo: "B04. 우설구이",
        nameEn: "Wooseul Gui",
        nameZh: "WOOSEUL GUI",
        price: "RM 90.00",
        descKo: "쫄깃하고 부드러운 맛이 일품인 얇게 썬 최고급 우설구이",
        descEn: "Thinly sliced Ox-tongue grilled over natural charcoal",
        descZh: "薄切牛舌",
        image: "assets/menu/woo_seul_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-11",
        category: "beef",
        nameKo: "B05. 소고기모둠",
        nameEn: "Beef Modum",
        nameZh: "BEEF MODUM",
        price: "RM 320.00",
        descKo: "소고기 4가지 부위 모둠 구성 (우설, 갈비본살, 차돌박이, 갈비살)",
        descEn: "Four kinds of assorted beef BBQ sampler (Ox tongue, boneless short rib, brisket, short rib)",
        descZh: "四种特选牛肉组合（牛舌、去骨牛小排、牛胸肉、牛肋条）",
        image: "assets/menu/beep_modum.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "beef-12",
        category: "beef",
        nameKo: "B06. LA 갈비",
        nameEn: "LA Galbi",
        nameZh: "LA GALBI",
        price: "RM 125.00",
        descKo: "뼈째 직각 방향으로 잘라 대파와 마늘을 넣은 특제 간장 양념에 재운 소갈비구이",
        descEn: "Short ribs cut through the bone and marinated in soy sauce, onion, and garlic",
        descZh: "LA排骨是将整条排骨切成与骨头呈直角方向，形成连骨带肉的T骨牛排，主要可做烧烤或炖排骨。",
        image: "assets/menu/la_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-13",
        category: "beef",
        nameKo: "B07. 갈비살주물럭",
        nameEn: "Galbisal",
        nameZh: "GALBISAL",
        price: "RM 125.00",
        descKo: "뼈를 바른 갈비살을 즉석에서 특제 마늘 간장 소스로 주물럭 조리한 구이",
        descEn: "Boneless short ribs marinated in garlic-based special sauce",
        descZh: "经大吾来特制酱汁腌制的无骨牛肋条",
        image: "assets/menu/galbi_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-14",
        category: "beef",
        nameKo: "B08. 우삼겹",
        nameEn: "Woosamgyeop",
        nameZh: "WOOSAMGYEOP",
        price: "RM 80.00",
        descKo: "부드럽고 지방이 풍부한 양념하지 않은 차돌 우삼겹살 구이",
        descEn: "Thinly sliced, richly marbled beef without marinade",
        descZh: "无调味薄切雪花肥牛",
        image: "assets/menu/woo_samgyeop.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-15",
        category: "pork",
        nameKo: "P01. 돼지스페셜",
        nameEn: "Pork Special",
        nameZh: "PORK SPECIAL",
        price: "RM 45.00",
        descKo: "돼지 머리에서 얻은 부드럽고 쫄깃한 식감의 특수 부위 (덜미살)",
        descEn: "Specially selected cuts of pork that is soft and tender",
        descZh: "严选软嫩猪面颊肉",
        image: "assets/menu/dwaeji_special.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-16",
        category: "pork",
        nameKo: "P02. 항정살",
        nameEn: "Hangjungsal",
        nameZh: "HANGJUNGSAL",
        price: "RM 45.00",
        descKo: "천겹살이라 불리는 돼지 목덜미의 쫄깃하고 마블링이 우수한 항정살 구이",
        descEn: "Pork Jowls grilled over natural charcoal",
        descZh: "炭烤切片猪颈肉（黄金六两）",
        image: "assets/menu/hang_jung_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-17",
        category: "pork",
        nameKo: "P03. 목살",
        nameEn: "Moksal",
        nameZh: "MOKSAL",
        price: "RM 38.00",
        descKo: "기름기가 적고 담백하여 숯불구이에 가장 적합한 신선한 목살 목등심",
        descEn: "Pork Shoulder cut into thick slices and grilled over charcoal",
        descZh: "炭烤新鲜猪梅花肉（肩胛肉）",
        image: "assets/menu/mok_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-18",
        category: "pork",
        nameKo: "P04. 삼겹살",
        nameEn: "Samgyeopsal",
        nameZh: "SAMGYEOPSAL",
        price: "RM 38.00",
        descKo: "살코기와 지방이 세 겹으로 되어 있어 부드럽고 고소한 삼겹살 구이",
        descEn: "Pork Belly grilled and dipped in salt or ssamjang (red soybean paste dip)",
        descZh: "五花肉是猪肚腩部位的肉，因瘦肉 和脂肪交替，所以肉质软嫩可口。一般是生肉 直接上火烤",
        image: "assets/menu/samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-19",
        category: "pork",
        nameKo: "P05. 고추장 삼겹살",
        nameEn: "Gochujang Samgyeopsal",
        nameZh: "GOCHUJANG SAMGYEOPSAL",
        price: "RM 42.00",
        descKo: "삼겹살에 매콤달콤한 고추장 양념을 버무려 숯불 향을 입힌 양념구이",
        descEn: "Pork belly marinated in spicy Korean chili paste",
        descZh: "将五花肉用辣椒酱做成的调味酱搅拌后，烤着吃或炒着吃即可。用辣椒酱调味的五花肉肥而不腻，非常香嫩。",
        image: "assets/menu/gochujang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-20",
        category: "pork",
        nameKo: "P06. 양념 돼지갈비",
        nameEn: "Yangnyeom Dwaeji Galbi",
        nameZh: "YANGNYEOM DWAEJI GALBI",
        price: "RM 42.00",
        descKo: "돼지갈비대를 특제 간장 양념장에 재워 육즙이 가득하고 감칠맛 나는 구이",
        descEn: "Pork marinated in soy sauce, garlic, and sweet onion marinade",
        descZh: "将猪排肉用调味汁腌渍以后放到炭 火上烤熟即可。",
        image: "assets/menu/yangnyeom_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-21",
        category: "pork",
        nameKo: "P07. 한방 돼지왕갈비",
        nameEn: "Hanbang Dwaeji Wang Galbi",
        nameZh: "HANBANG DWAEJI WANG GALBI",
        price: "RM 48.00",
        descKo: "칼집을 낸 큼직한 돼지갈비를 엄선된 인삼, 약초 추출물과 특제 간장에 잰 건강 구이",
        descEn: "Pork ribs marinated in Korean ginseng, herb extracts, and soy sauce",
        descZh: "经秘制人参、韩方草本提取物及大吾来特制酱汁腌制的特选大猪排",
        image: "assets/menu/hanbang_dwaeji_wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-22",
        category: "pork",
        nameKo: "P08. 돼지 주물럭",
        nameEn: "Dwaeji Jumulluk",
        nameZh: "DWAEJI JUMULLUK",
        price: "RM 47.00",
        descKo: "엄선한 돼지고기 살코기를 즉석에서 마늘과 달콤한 다오래 간장 소스에 조리한 주물럭",
        descEn: "Selected cuts of soft pork marinated in special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的软嫩猪肋条肉",
        image: "assets/menu/dwaeji_jumulluk.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-23",
        category: "pork",
        nameKo: "P09. 매운 돼지갈비",
        nameEn: "Maeun Dwaeji Galbi",
        nameZh: "MAEUN DWAEJI BALLBI",
        price: "RM 42.00",
        descKo: "수제 손질한 엄선된 돼지고기를 매콤한 한국식 고추장 양념장에 재운 구이",
        descEn: "Pork marinated in spicy Korean chili sauce and soy sauce",
        descZh: "经韩式辣酱腌制的纯手工特选辣猪排",
        image: "assets/menu/maeun_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-24",
        category: "pork",
        nameKo: "P10. 한방 삼겹살",
        nameEn: "Hanbang Samgyeopsal",
        nameZh: "HANBANG SAMGYEOPSAL",
        price: "RM 45.00",
        descKo: "신선한 삼겹살에 특제 인삼 및 몸에 좋은 한방 약초 추출물을 입혀 숙성시킨 삼겹살 구이",
        descEn: "Slices of pork belly marinated in special Korean ginseng and herbs extract",
        descZh: "经秘制人参及韩方草本提取物腌制的切片五花肉",
        image: "assets/menu/hanbang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "other-bbq-25",
        category: "other-bbq",
        nameKo: "M01. 양념 닭갈비",
        nameEn: "Yangnyeom Dakgalbi",
        nameZh: "YANGNYEOM DAKGALBI",
        price: "RM 38.00",
        descKo: "부드러운 닭다리살을 고추장 양념장에 재웠다가 숯불에 구워 먹는 강원도 춘천식 별미 요리",
        descEn: "Chicken marinated in Daorae sauce and cooked on a charcoal grill",
        descZh: "鸡肉用辣椒酱调制的调味酱腌一会儿，入味后放在炭火上烤熟即可",
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-26",
        category: "other-bbq",
        nameKo: "M02. 닭갈비",
        nameEn: "Dak Galbi",
        nameZh: "DAK GALBI",
        price: "RM 38.00",
        descKo: "지방이 적고 담백한 닭가슴살 및 닭정육 부위를 청양 고춧가루 특제 매운 양념에 재운 요리",
        descEn: "Lean skinless chicken fillets marinated in our hot chili sauce",
        descZh: "辣味调酱腌制的去皮去骨无脂鸡胸肉",
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-27",
        category: "other-bbq",
        nameKo: "M03. 양념 양고기",
        nameEn: "Yangnyeom Yanggogi",
        nameZh: "YANGNYEOM YANGGOGI",
        price: "RM 52.00",
        descKo: "엄선한 고급 양고기 살코기를 수제 손질하여 다오래 특제 갈비 소스에 버무려 구운 양고기",
        descEn: "Chosen cuts of lamb specially hand filleted, marinated in special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的特选纯手工羊肉",
        image: "assets/menu/yangnyeom_yanggogi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "other-bbq-28",
        category: "other-bbq",
        nameKo: "M04. 양념 오징어구이",
        nameEn: "Yangnyeom Ojingeo Gui",
        nameZh: "YANGNYEOM OJINGEO GUI",
        price: "RM 57.00",
        descKo: "신선하고 통통한 오징어에 칼집을 내어 다오래 특제 고추장 매운 소스를 곁들여 석쇠에 구운 요리",
        descEn: "Fresh squid carved and prepared in our hot chili sauce",
        descZh: "经特制辣酱调味烤制的新鲜鱿鱼",
        image: "assets/menu/yangnyeom_ojingeo_gui.png",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "other-bbq-29",
        category: "other-bbq",
        nameKo: "M05. 양념 쭈꾸미구이",
        nameEn: "Yangnyeom Jukkumi Gui",
        nameZh: "YANGNYEOM JUKKUMI GUI",
        price: "RM 57.00",
        descKo: "신선한 쭈꾸미를 손질해 불 맛 가득한 다오래 고추장 특제 매운 양념 소스에 맛있게 구운 요리",
        descEn: "Fresh baby octopus carved and prepared in our hot chili sauce",
        descZh: "经特制辣酱调味烤制的新鲜小八爪鱼",
        image: "assets/menu/jjuggumi_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 3
    },
    {
        id: "stew-30",
        category: "stew",
        nameKo: "S01. 김치찌개",
        nameEn: "Kimchi Jjigae",
        nameZh: "KIMCHI JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "푹 익은 신김치에 부드러운 돼지고기, 고소한 두부, 대파를 듬뿍 넣어 얼큰하고 깊은 맛을 낸 한국인의 소울푸드",
        descEn: "Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean soul food.",
        descZh: "将酸泡菜放入锅中，再加入猪肉、豆腐以及切成粗丝的葱等材料炖煮即可。",
        image: "assets/menu/kimchi_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-31",
        category: "stew",
        nameKo: "S02. 된장찌개",
        nameEn: "Doenjang Jjigae",
        nameZh: "DOENJANG JJIGAE (SEAFOOD)",
        price: "RM 30.00",
        descKo: "멸치 육수에 구수한 재래식 된장을 풀고 신선한 조개류, 두부, 애호박을 넣어 끓인 밥도둑 찌개",
        descEn: "Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash.",
        descZh: "高汤中放入大酱，再加入肉、鱼贝类、豆腐、西葫芦等熬煮即可。",
        image: "assets/menu/doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-32",
        category: "stew",
        nameKo: "S03. 순두부찌개",
        nameEn: "Sundubu Jjigae",
        nameZh: "SUNDUBU JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "몽글몽글한 순두부와 다진 돼지고기, 신선한 야채를 넣고 얼큰한 고추기름 육수로 맛을 낸 찌개 (날달걀 추가 가능)",
        descEn: "Soft bean curd stew boiled with minced pork and vegetables in a spicy red chili broth.",
        descZh: "在砂锅中放入嫩豆腐和猪肉、蔬菜，再加入辣高汤, 顶上面打入新鲜鸡蛋",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-33",
        category: "stew",
        nameKo: "S04. 해물순두부찌개",
        nameEn: "Haemul Sundubu Jjigae",
        nameZh: "HAEMUL SUNDUBU JJIGAE (SEAFOOD)",
        price: "RM 28.00",
        descKo: "부드러운 순두부에 신선한 게, 새우, 조개류 등 모듬 해물을 듬뿍 넣어 바다의 시원하고 얼큰한 맛을 살린 찌개",
        descEn: "Soft bean curd stew boiled with assorted seafood (shrimps, clams) in a spicy, flavorful broth.",
        descZh: "在砂锅中放入嫩豆腐和虾、蛤蜊等海鲜，再加入高汤熬煮而成，吃起来十分爽口",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-34",
        category: "stew",
        nameKo: "S05. 보스된장찌개",
        nameEn: "Boss Doenjang Jjigae",
        nameZh: "BOSS DOENJANG JJIGAE (BEEF)",
        price: "RM 30.00",
        descKo: "진하게 끓인 전통 한식 된장 육수에 부드러운 차돌박이 소고기, 두부, 야채를 아낌없이 넣은 프리미엄 된장찌개",
        descEn: "Tofu and fresh vegetables in a rich traditional Korean bean broth topped with beef, served with rice.",
        descZh: "在传统的韩式浓郁大酱汤中加入牛肉、豆腐和新鲜蔬菜熬制的大酱汤",
        image: "assets/menu/boss_doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-35",
        category: "stew",
        nameKo: "S08. 갈비탕",
        nameEn: "Galbitang",
        nameZh: "GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "핏물을 뺀 소갈비와 큼직한 무를 가마솥에서 푹 고아 맑고 시원한 육수가 일품인 대표 보양식 갈비탕",
        descEn: "Beef ribs and white radish chunks simmered together until tender. The clear stock is rich and savory.",
        descZh: "用牛排骨熬的汤，牛排骨浸泡去血后与萝卜一起熬煮至肉烂，不但汤汁香醇",
        image: "assets/menu/galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-36",
        category: "stew",
        nameKo: "S09. 우거지갈비탕",
        nameEn: "Ugeoji Galbitang",
        nameZh: "UGEOJI GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "소갈비를 끓여낸 육수에 구수한 시골 된장과 식이섬유가 풍부한 우거지를 푹 끓여내어 위장에 좋은 건강 탕",
        descEn: "Napa cabbage leaves slowly simmered in a beef rib stock and seasoned with traditional doenjang (soybean paste).",
        descZh: "用排骨长时间熬煮制成高汤，再放入泡发的干白菜和大酱熬煮。",
        image: "assets/menu/ugeoji_galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-37",
        category: "stew",
        nameKo: "S10. 육개장",
        nameEn: "Yukgaejang",
        nameZh: "YUKGAEJANG (BEEF)",
        price: "RM 38.00",
        descKo: "소 양지머리를 고아 고사리, 대파, 토란대 등의 나물을 넣고 붉은 고추기름으로 맵고 얼큰하게 양념한 보양식",
        descEn: "A spicy soup made of shredded beef brisket, radish, green onions, bean sprouts, and fiddleheads.",
        descZh: "用牛的排骨 and 萝卜等长时间熬煮，再加入大葱、青芋茎、蕨菜 and 辣椒粉等调味而成。",
        image: "assets/menu/yukgaejang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 2
    },
    {
        id: "hotpot-38",
        category: "hotpot",
        nameKo: "S03. 순두부찌개",
        nameEn: "Sundubu Jjigae",
        nameZh: "SUNDUBU JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "몽글몽글한 순두부와 다진 돼지고기, 신선한 야채를 넣고 얼큰한 고추기름 육수로 맛을 낸 찌개 (날달걀 추가 가능)",
        descEn: "Soft bean curd stew boiled with minced pork and vegetables in a spicy red chili broth.",
        descZh: "在砂锅中放入嫩豆腐和猪肉、蔬菜，再加入辣高汤, 顶上面打入新鲜鸡蛋",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "hotpot-39",
        category: "hotpot",
        nameKo: "S01. 김치찌개",
        nameEn: "Kimchi Jjigae",
        nameZh: "KIMCHI JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "푹 익은 신김치에 부드러운 돼지고기, 고소한 두부, 대파를 듬뿍 넣어 얼큰하고 깊은 맛을 낸 한국인의 소울푸드",
        descEn: "Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean soul food.",
        descZh: "将酸泡菜放入锅中，再加入猪肉、豆腐以及切成粗丝의葱等材料炖煮即可。",
        image: "assets/menu/kimchi_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "hotpot-40",
        category: "hotpot",
        nameKo: "S02. 된장찌개",
        nameEn: "Doenjang Jjigae",
        nameZh: "DOENJANG JJIGAE (SEAFOOD)",
        price: "RM 30.00",
        descKo: "멸치 육수에 구수한 재래식 된장을 풀고 신선한 조개류, 두부, 애호박을 넣어 끓인 밥도둑 찌개",
        descEn: "Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash.",
        descZh: "高汤中放入大酱，再加入肉、鱼贝类、豆腐、西葫芦等熬煮即可。",
        image: "assets/menu/doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-41",
        category: "hotpot",
        nameKo: "S05. 보스된장찌개",
        nameEn: "Boss Doenjang Jjigae",
        nameZh: "BOSS DOENJANG JJIGAE (BEEF)",
        price: "RM 30.00",
        descKo: "진하게 끓인 전통 한식 된장 육수에 부드러운 차돌박이 소고기, 두부, 야채를 아낌없이 넣은 프리미엄 된장찌개",
        descEn: "Tofu and fresh vegetables in a rich traditional Korean bean broth topped with beef, served with rice.",
        descZh: "在传统的韩式浓郁大酱汤中加入牛肉、豆腐和新鲜蔬菜熬制的大酱汤",
        image: "assets/menu/boss_doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-42",
        category: "hotpot",
        nameKo: "S08. 갈비탕",
        nameEn: "Galbitang",
        nameZh: "GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "핏물을 뺀 소갈비와 큼직한 무를 가마솥에서 푹 고아 맑고 시원한 육수가 일품인 대표 보양식 갈비탕",
        descEn: "Beef ribs and white radish chunks simmered together until tender. The clear stock is rich and savory.",
        descZh: "用牛排骨熬的汤，牛排骨浸泡去血后与萝卜一起熬煮至肉烂，不但汤汁香醇",
        image: "assets/menu/galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-43",
        category: "hotpot",
        nameKo: "S09. 우거지갈비탕",
        nameEn: "Ugeoji Galbitang",
        nameZh: "UGEOJI GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "소갈비를 끓여낸 육수에 구수한 시골 된장과 식이섬유가 풍부한 우거지를 푹 끓여내어 위장에 좋은 건강 탕",
        descEn: "Napa cabbage leaves slowly simmered in a beef rib stock and seasoned with traditional doenjang (soybean paste).",
        descZh: "用排骨长时间熬煮制成高汤，再放入泡发的干白菜和大酱熬煮。",
        image: "assets/menu/ugeoji_galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-44",
        category: "hotpot",
        nameKo: "S10. 육개장",
        nameEn: "Yukgaejang",
        nameZh: "YUKGAEJANG (BEEF)",
        price: "RM 38.00",
        descKo: "소 양지머리를 고아 고사리, 대파, 토란대 등의 나물을 넣고 붉은 고추기름으로 맵고 얼큰하게 양념한 보양식",
        descEn: "A spicy soup made of shredded beef brisket, radish, green onions, bean sprouts, and fiddleheads.",
        descZh: "用牛的排骨 and 萝卜等长时间熬煮，再加入大葱、青芋茎、蕨菜 and 辣椒粉等调味而成。",
        image: "assets/menu/yukgaejang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 2
    },
    {
        id: "rice-45",
        category: "rice",
        nameKo: "R01. 돌솥비빔밥",
        nameEn: "Dolsot Bibimbap",
        nameZh: "DOLSOT BIBIMBAP",
        price: "RM 30.00",
        descKo: "뜨거운 돌솥에 밥과 신선한 오색 나물, 볶은 소고기, 계란 노른자를 올려 고추장에 비벼 먹는 한식 대표 비빔밥",
        descEn: "Bibimbap served in a sizzling hot stone pot. The crispy rice at the bottom, mixed with various toppings and gochujang.",
        descZh: "在加热의石锅中分别放入米饭、各种素菜和炒肉丝，用辣椒酱或酱油搅拌即可。",
        image: "assets/menu/dolsot_bibimbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-46",
        category: "rice",
        nameKo: "R03. 소불고기볶음밥",
        nameEn: "Beef Bulgogi Bokkeumbap",
        nameZh: "BEEF BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "부드럽고 짭조름한 소불고기와 야채를 밥과 함께 철판에서 고소하게 볶아낸 소불고기 볶음밥",
        descEn: "Stir-fried rice with tender, savory beef bulgogi and fresh vegetables.",
        descZh: "香浓烤牛肉与大米饭和蔬菜在铁板上炒制的美味烤肉炒饭",
        image: "assets/menu/beep_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-47",
        category: "rice",
        nameKo: "R04. 돼지불고기볶음밥",
        nameEn: "Dwaeji Bulgogi Bokkeumbap",
        nameZh: "DWAEJI BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "매콤달콤한 고추장 돼지불고기 소스로 밥과 야채를 맛있게 불 맛나게 볶아낸 볶음밥",
        descEn: "Stir-fried rice with sweet and spicy pork bulgogi and assorted vegetables.",
        descZh: "韩式辣炒猪肉与米饭及鲜疏一起炒制的高感度猪肉炒饭",
        image: "assets/menu/dwaeji_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-48",
        category: "rice",
        nameKo: "R05. 김치볶음밥",
        nameEn: "Kimchi Bokkeumbap",
        nameZh: "KIMCHI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "신김치와 베이컨 또는 고기를 볶은 뒤 참기름을 두른 볶음밥 위에 바삭한 계란후라이를 얹은 요리",
        descEn: "Kimchi fried rice with meat, topped with a fried egg and seaweed flakes.",
        descZh: "泡菜和米饭炒制，并配以煎蛋的泡菜炒饭",
        image: "assets/menu/kimchi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-49",
        category: "rice",
        nameKo: "R06. 잡채볶음밥",
        nameEn: "Japchae Bokkeumbap",
        nameZh: "JAPCHAE BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "한식 잔치 요리인 당면 잡채와 밥을 함께 센 불에 볶아낸 쫄깃하고 고소한 잡채 볶음밥",
        descEn: "Korean glass noodle (Japchae) and rice pan fried with assorted seasoned vegetables.",
        descZh: "韩式杂菜（红薯淀粉粉丝）与各类调味蔬菜和米饭同炒的杂菜炒饭",
        image: "assets/menu/japchae_bokkeumbap.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-50",
        category: "rice",
        nameKo: "R07. 주먹밥",
        nameEn: "Jumeokbap",
        nameZh: "JUMEOKBAP",
        price: "RM 20.00",
        descKo: "따뜻한 밥에 고소한 참기름, 통깨, 조미 김가루를 조물조물 버무려 한 입 크기로 동글동글하게 뭉친 주먹밥",
        descEn: "Hand-rolled rice balls seasoned with fragrant sesame oil, sesame seeds, and seaweed flakes.",
        descZh: "拌入海苔碎和蔬菜手工捏成的圆形饭团",
        image: "assets/menu/jumeokbap.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "rice-51",
        category: "rice",
        nameKo: "R08. 공기밥",
        nameEn: "Bap",
        nameZh: "BAP",
        price: "RM 6.00",
        descKo: "매장에서 매일 신선하게 지은 고슬고슬하고 찰진 흰 쌀밥 공기밥",
        descEn: "Freshly steamed white sticky rice bowl.",
        descZh: "白米饭",
        image: "assets/menu/bap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-52",
        category: "noodle",
        nameKo: "N03. 물냉면",
        nameEn: "Mul Naengmyeon",
        nameZh: "MUL NAENGMYEON",
        price: "RM 28.00",
        descKo: "메밀 면을 삶아 동치미 국물과 소고기 육수 섞은 국물에 차갑게 말아 먹는 음식이다. 무, 배, 등을 얹고 겨자와 식초로 양념한다.",
        descEn: "Buckwheat noodles served in chilled soup made of dongchimi (radish kimchi) liquid and beef broth.",
        descZh: "用白萝卜泡菜汤汁和牛肉高汤调成冰镇汤汁，放入煮熟的荞麦面，再加入一些萝卜、梨等装饰配菜",
        image: "assets/menu/mul_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-53",
        category: "noodle",
        nameKo: "N04. 비빔냉면",
        nameEn: "Bibim Naengmyeon",
        nameZh: "BIBIM NAENGMYEON",
        price: "RM 28.00",
        descKo: "메밀로 만든 면을 삶아 찬물에 헹궈 물기를 뺀 다음 소고기 편육이나 홍어회무침, 무, 오이, 삶은 계란 등을 얹고 고추장 양념장에 비벼 차갑게 먹는 음식이다.",
        descEn: "Chilled buckwheat noodles garnished with cold slices of beef, skate, and radish or cucumber. Served with a spicy gochujang mixing sauce.",
        descZh: "拌冷面多使用荞麦面。荞麦面煮熟后用凉水冲洗并沥干水分，然后放入白切牛肉片",
        image: "assets/menu/bibim_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-54",
        category: "noodle",
        nameKo: "N05. 김치비빔국수",
        nameEn: "Kimchi Bibim Guksu",
        nameZh: "KIMCHI BIBIM GUKSU",
        price: "RM 28.00",
        descKo: "새콤하게 익은 김치를 썰어 넣고 고추장, 참기름으로 비벼 낸 매콤 새콤한 한국 전통 비빔국수",
        descEn: "Chilled wheat noodles tossed in a sweet, sour, and spicy chili sauce topped with chopped Kimchi.",
        descZh: "配以辣泡菜的冰凉辣拌面",
        image: "assets/menu/image_5d08b9_3.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-55",
        category: "noodle",
        nameKo: "N06. 김치말이국수",
        nameEn: "Kimchimari Guksu",
        nameZh: "KIMCHIMARI GUKSU",
        price: "RM 28.00",
        descKo: "동치밋국이나 열무 김칫국 또는 김칫국을 섞은 육수에 삶아 낸 국수를 넣어 시원하게 먹는 음식이다.",
        descEn: "This is a noodle dish made with chilled dongchimi soup or kimchi soup mixed with beef stock and topped with beef.",
        descZh: "用水萝卜泡菜或萝卜缨泡菜、泡菜等的汤汁调和高汤备用，面条煮熟后放入冰镇的高汤",
        image: "assets/menu/kimchi_mari_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-56",
        category: "noodle",
        nameKo: "N07. 잔치국수",
        nameEn: "Janchi Guksu",
        nameZh: "JANCHI GUKSU",
        price: "RM 28.00",
        descKo: "삶은 국수에 계란지단 등으로 고명을 얹고 멸치장국을 부어낸 국수로 예로부터 잔치 때 손님을 대접하는 대표 음식이다.",
        descEn: "Thin wheat noodles served in a hot, clear anchovy broth with egg, zucchini, and seaweed garnish.",
        descZh: "在煮熟的面条上放鸡蛋丝等菜码，再浇上鳀鱼汤汁而成。自古用来在婚宴、生日宴招待宾客。",
        image: "assets/menu/janchi_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-57",
        category: "noodle",
        nameKo: "N08. 라면",
        nameEn: "Ramyeon",
        nameZh: "RAMYEON",
        price: "RM 23.00",
        descKo: "양은 냄비에 끓여 낸 얼큰하고 꼬들꼬들한 한국식 인스턴트 매운 라면 (계란 및 파 송송 포함)",
        descEn: "Spicy and savory Korean instant noodle cooked in a hot brass pot with eggs and green onion.",
        descZh: "香辣浓郁的韩式即食方便拉面",
        image: "assets/menu/ramyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-58",
        category: "other-cuisine",
        nameKo: "R01. 돌솥비빔밥",
        nameEn: "Dolsot Bibimbap",
        nameZh: "DOLSOT BIBIMBAP",
        price: "RM 30.00",
        descKo: "뜨거운 돌솥에 밥과 신선한 오색 나물, 볶은 소고기, 계란 노른자를 올려 고추장에 비벼 먹는 한식 대표 비빔밥",
        descEn: "Bibimbap served in a sizzling hot stone pot. The crispy rice at the bottom, mixed with various toppings and gochujang.",
        descZh: "在加热의石锅中分别放入米饭、各种素菜 and 炒肉丝，用辣椒酱或酱油搅拌即可。",
        image: "assets/menu/dolsot_bibimbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-59",
        category: "other-cuisine",
        nameKo: "R03. 소불고기볶음밥",
        nameEn: "Beef Bulgogi Bokkeumbap",
        nameZh: "BEEF BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "부드럽고 짭조름한 소불고기오 야채를 밥과 함께 철판에서 고소하게 볶아낸 소불고기 볶음밥",
        descEn: "Stir-fried rice with tender, savory beef bulgogi and fresh vegetables.",
        descZh: "香浓烤牛肉与大米饭和蔬菜在铁板上炒制的美味烤肉炒饭",
        image: "assets/menu/beep_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-60",
        category: "other-cuisine",
        nameKo: "R04. 돼지불고기볶음밥",
        nameEn: "Dwaeji Bulgogi Bokkeumbap",
        nameZh: "DWAEJI BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "매콤달콤한 고추장 돼지불고기 소스로 밥과 야채를 맛있게 불 맛나게 볶아낸 볶음밥",
        descEn: "Stir-fried rice with sweet and spicy pork bulgogi and assorted vegetables.",
        descZh: "韩式辣炒猪肉与米饭及鲜疏一起炒制的高感度猪肉炒饭",
        image: "assets/menu/dwaeji_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-61",
        category: "other-cuisine",
        nameKo: "R05. 김치볶음밥",
        nameEn: "Kimchi Bokkeumbap",
        nameZh: "KIMCHI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "신김치와 베이컨 또는 고기를 볶은 뒤 참기름을 두른 볶음밥 위에 바삭한 계란후라이를 얹은 요리",
        descEn: "Kimchi fried rice with meat, topped with a fried egg and seaweed flakes.",
        descZh: "泡菜和米饭炒制，并配以煎蛋的泡菜炒饭",
        image: "assets/menu/kimchi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-62",
        category: "other-cuisine",
        nameKo: "R06. 잡채볶음밥",
        nameEn: "Japchae Bokkeumbap",
        nameZh: "JAPCHAE BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "한식 잔치 요리인 당면 잡채와 밥을 함께 센 불에 볶아낸 쫄깃하고 고소한 잡채 볶음밥",
        descEn: "Korean glass noodle (Japchae) and rice pan fried with assorted seasoned vegetables.",
        descZh: "韩式杂菜（红薯淀粉粉丝）与各类调味蔬菜和米饭同炒的杂菜炒饭",
        image: "assets/menu/japchae_bokkeumbap.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-63",
        category: "other-cuisine",
        nameKo: "R07. 주먹밥",
        nameEn: "Jumeokbap",
        nameZh: "JUMEOKBAP",
        price: "RM 20.00",
        descKo: "따뜻한 밥에 고소한 참기름, 통깨, 조미 김가루를 조물조물 버무려 한 입 크기로 동글동글하게 뭉친 주먹밥",
        descEn: "Hand-rolled rice balls seasoned with fragrant sesame oil, sesame seeds, and seaweed flakes.",
        descZh: "拌入海苔碎和蔬菜手工捏成的圆形饭团",
        image: "assets/menu/jumeokbap.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-64",
        category: "other-cuisine",
        nameKo: "R08. 공기밥",
        nameEn: "Bap",
        nameZh: "BAP",
        price: "RM 6.00",
        descKo: "매장에서 매일 신선하게 지은 고슬고슬하고 찰진 흰 쌀밥 공기밥",
        descEn: "Freshly steamed white sticky rice bowl.",
        descZh: "白米饭",
        image: "assets/menu/bap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-65",
        category: "dosilak",
        nameKo: "L02. 불고기도시락",
        nameEn: "Bulgogi Dosilak",
        nameZh: "BULGOGI DOSILAK",
        price: "RM 25.00",
        descKo: "불고기, 밥, 반찬이 어우러진 알찬 소불고기 도시락",
        descEn: "Slices of prime beef simmered in its own juices and a special soya sauce broth served in a lunchbox.",
        descZh: "包含烤牛肉、米饭及各式配菜的韩式烤牛肉便当",
        image: "assets/menu/bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-66",
        category: "dosilak",
        nameKo: "L03. 돼지불고기도시락",
        nameEn: "DejiBulgogi Dosilak",
        nameZh: "DEJIBULGOGI DOSILAK",
        price: "RM 25.00",
        descKo: "매콤한 돼지불고기와 밥, 반찬이 어우러진 도시락",
        descEn: "Pork and assortment of vegetables stir-fried with Korean chili paste served in a lunchbox.",
        descZh: "包含辣炒猪肉、米饭及各式配菜的韩式辣炒猪肉便当",
        image: "assets/menu/dwaeji_bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-67",
        category: "dosilak",
        nameKo: "L04. 오징어볶음도시락",
        nameEn: "Ojingeo Bokeum Dosilak",
        nameZh: "OJINGEO BOKEUM DOSILAK",
        price: "RM 25.00",
        descKo: "매콤한 오징어볶음과 밥, 반찬이 함께 들어간 도시락",
        descEn: "Fried squid in a sauce of Korean chili paste served in a lunchbox.",
        descZh: "包含辣炒鱿鱼、米饭及各式配菜的韩式辣炒鱿鱼便当",
        image: "assets/menu/ojingeo_bokkeum_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-68",
        category: "dosilak",
        nameKo: "L05. 보쌈도시락",
        nameEn: "Bossam Dosilak",
        nameZh: "BOSSAM DOSILAK",
        price: "RM 25.00",
        descKo: "부드러운 수육 보쌈과 무말랭이, 밥, 반찬이 어우러진 도시락",
        descEn: "Special recipe steamed tender pork belly served in a lunchbox with side dishes.",
        descZh: "包含特制秘方清蒸软嫩白切肉、米饭及各式配菜的韩式白切肉便当",
        image: "assets/menu/bossam_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-69",
        category: "dosilak",
        nameKo: "L07. 김치볶음도시락",
        nameEn: "Kimchi Bokkeum Dosilak",
        nameZh: "KIMCHI BOKKEUM DOSILAK",
        price: "RM 25.00",
        descKo: "매콤하게 볶아낸 삼겹살 김치볶음과 밥, 반찬이 어우러진 도시락",
        descEn: "Belly pork fried with Kimchi served in a lunchbox with side dishes.",
        descZh: "包含泡菜炒五花肉、米饭及各式配菜的韩式泡菜炒肉便当",
        image: "assets/menu/kimchi_bokkeum_dosilak.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "beverage-70",
        category: "beverage",
        nameKo: "V01. Coke",
        nameEn: "Coke",
        nameZh: "COKE",
        price: "RM 5.00",
        descKo: "코카콜라 탄산음료 (캔)",
        descEn: "CocaCola Soda Drink (Can)",
        descZh: "罐装可口可乐碳酸饮料",
        image: "assets/menu/coke.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-71",
        category: "beverage",
        nameKo: "V02. Sprite",
        nameEn: "Sprite",
        nameZh: "SPRITE",
        price: "RM 5.00",
        descKo: "스프라이트 탄산음료 (캔)",
        descEn: "Sprite Soda Drink (Can)",
        descZh: "罐装雪碧碳酸饮料",
        image: "assets/menu/sprite.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-72",
        category: "beverage",
        nameKo: "V03. 100 Plus",
        nameEn: "100 Plus",
        nameZh: "100 PLUS",
        price: "RM 5.00",
        descKo: "백플러스 이온음료 (캔)",
        descEn: "100 Plus Isotonic Drink (Can)",
        descZh: "罐装100 Plus等渗离子饮料",
        image: "assets/menu/100_plus.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-73",
        category: "beverage",
        nameKo: "V04. Galamanddeunbae",
        nameEn: "Galamanddeunbae",
        nameZh: "GALAMANDDEUNBAE",
        price: "RM 7.00",
        descKo: "국산 해태 갈아만든 배 시원한 음료 (캔)",
        descEn: "Korean Crushed Pear Juice (Can)",
        descZh: "罐装韩国海太碎梨汁",
        image: "assets/menu/galamanddeunbae.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-74",
        category: "beverage",
        nameKo: "V05. 소주",
        nameEn: "Soju",
        nameZh: "SOJU",
        price: "RM 35.00",
        descKo: "한국 전통 소주 주류",
        descEn: "Traditional Korean Liquor (Soju)",
        descZh: "韩国传统烧酒",
        image: "assets/menu/soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-75",
        category: "beverage",
        nameKo: "V08. 레몬소주",
        nameEn: "Lemon Soju",
        nameZh: "LEMON SOJU",
        price: "RM 38.00",
        descKo: "상큼한 레몬을 블렌딩한 상쾌한 과일 소주",
        descEn: "Korean Liquor with Lemon",
        descZh: "柠檬风味烧酒",
        image: "assets/menu/lemon_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-76",
        category: "beverage",
        nameKo: "V09. 오이소주",
        nameEn: "Cucumber Soju",
        nameZh: "CUCUMBER SOJU",
        price: "RM 38.00",
        descKo: "시원하고 깔끔한 맛을 자랑하는 수제 오이 소주",
        descEn: "Korean Liquor infused with fresh Cucumber slices",
        descZh: "黄瓜风味烧酒",
        image: "assets/menu/cucumber_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-77",
        category: "beverage",
        nameKo: "V10. 타이거캔맥주",
        nameEn: "Tiger Beer (Can)",
        nameZh: "TIGER BEER (CAN)",
        price: "RM 13.00",
        descKo: "청량감이 넘치는 수입 타이거 캔맥주",
        descEn: "Tiger Beer (Can)",
        descZh: "罐装虎牌啤酒",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-78",
        category: "beverage",
        nameKo: "V11. 타이거병맥주",
        nameEn: "Tiger Beer (Bottle)",
        nameZh: "TIGER BEER (BOTTLE)",
        price: "RM 30.00",
        descKo: "시원하고 풍미가 살아있는 오리지널 타이거 병맥주",
        descEn: "Tiger Beer (Bottle)",
        descZh: "瓶装虎牌啤酒",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-79",
        category: "beverage",
        nameKo: "V12. 한국병맥주",
        nameEn: "Korean Beer",
        nameZh: "KOREAN BEER",
        price: "RM 35.00",
        descKo: "한국 전통 라거 병맥주 (카스 또는 테라)",
        descEn: "Korean Beer (Bottle, e.g. Cass or Terra)",
        descZh: "瓶装韩国啤酒（Cass/Terra）",
        image: "assets/menu/korean_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-80",
        category: "beverage",
        nameKo: "V13. 오십세주",
        nameEn: "OShipSaeJu",
        nameZh: "OSHIPSaeJu",
        price: "RM 90.00",
        descKo: "소주와 백세주를 황금 비율로 섞어 차갑게 즐기는 한국 특제 믹스 약주",
        descEn: "Combination of Soju & BaekSaeJu in an ice chilled bottle.",
        descZh: "冰镇瓶装五十岁酒（烧酒与百岁酒的黄金比例调和酒）",
        image: "assets/menu/oshipsaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-81",
        category: "beverage",
        nameKo: "V14. 백세주",
        nameEn: "BaekSaeJu",
        nameZh: "BAEKSAEJU",
        price: "RM 60.00",
        descKo: "12가지 한약재를 넣어 빚은 깊은 맛의 한국 전통 한방 약주",
        descEn: "Korean Herbal Liquor brewed with 12 organic herbs.",
        descZh: "百岁酒（融合十二种草本药材酿制的传统韩国养生酒）",
        image: "assets/menu/baeksaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-82",
        category: "beverage",
        nameKo: "V15. 설중매",
        nameEn: "SeolJungMae",
        nameZh: "SEOLJUNGMAE",
        price: "RM 65.00",
        descKo: "신선한 매실을 통째로 침출시켜 달콤하고 상큼한 프리미엄 매실주",
        descEn: "Korean Plum Wine featuring real green plums in the bottle.",
        descZh: "雪中梅（采用优质青梅酿制的韩国高级梅子酒）",
        image: "assets/menu/seoljungmae.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-83",
        category: "beverage",
        nameKo: "V16. 복분자",
        nameEn: "BokBunJa",
        nameZh: "BOKBUNJA",
        price: "RM 65.00",
        descKo: "달콤하고 떫은맛의 균형이 조화로운 건강 식물성 복분자주",
        descEn: "Korean Raspberry Wine known for its sweet, rich berry flavor and health benefits.",
        descZh: "覆盆子酒（采用优质覆盆子酿制的甘甜韩国覆盆子酒）",
        image: "assets/menu/bokbunja.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    }
];
