// DAORAE KOREAN BBQ - BUKIT INDAH OUTLET
// Trilingual Menu Database File (Korean, English, Chinese)
// Updated prices matching official Bukit Indah menu.pdf

const MENU_ITEMS = [
    // --------------------------------------------------------
    // JOHOR SPECIALS
    // --------------------------------------------------------
    {
        id: "johor-jb01",
        category: "johor-special",
        nameKo: "JB01. 주꾸미우삼겹",
        nameEn: "Jukkumi Usamgyeop",
        nameZh: "小八爪鱼炒肥牛",
        price: "RM 90.00",
        descKo: "매콤한 양념 쭈꾸미와 부드러운 우삼겹, 그리고 아삭한 콩나물 등 신선한 채소를 철판에서 매콤하게 볶아낸 별미 요리",
        descEn: "Stir-fried spicy webfoot octopus with thinly sliced beef short plate and assorted fresh vegetables.",
        descZh: "Q弹香辣小八爪鱼与薄切牛五花肉及新鲜蔬菜（如豆芽）同炒的美味料理",
        image: "assets/menu/jb01.png",
        badge: "Johor Only",
        serving: "2-3 Pax",
        spicy: 2
    },
    {
        id: "johor-jb02",
        category: "johor-special",
        nameKo: "JB02. 보쌈낙지볶음",
        nameEn: "Bossam Nakji Bokkeum",
        nameZh: "白切肉配辣炒章鱼",
        price: "RM 90.00",
        descKo: "부드럽고 촉촉하게 삶아낸 돼지 보쌈 수육과 매콤하고 쫄깃하게 볶아낸 불맛 낙지볶음을 함께 곁들여 먹는 고급 별미",
        descEn: "Tender and juicy boiled pork slices served alongside flavorful, fiery stir-fried octopus.",
        descZh: "软嫩多汁的清蒸猪五花肉（白切肉）配以香辣劲道爆炒章鱼的经典双拼",
        image: "assets/menu/jb02.png",
        badge: "Johor Only",
        serving: "2-3 Pax",
        spicy: 2
    },
    {
        id: "johor-jb03",
        category: "johor-special",
        nameKo: "JB03. 감자탕",
        nameEn: "Gamjatang",
        nameZh: "土豆猪骨汤",
        price: "RM 65.00",
        descKo: "살코기가 푸짐한 돼지 등뼈와 감자, 시래기, 들깨가루를 듬뿍 넣어 얼큰하고 구수하게 끓여낸 대표 한국식 해장 전골",
        descEn: "Rich and spicy hot pot stew made with tender pork neck bones, whole potatoes, and wild sesame powder.",
        descZh: "精选带肉猪脊骨与整块土豆、干白菜和苏子粉同熬的香辣浓郁土豆猪骨汤",
        image: "assets/menu/jb03.png",
        badge: "Johor Only",
        serving: "2-3 Pax",
        spicy: 1
    },
    {
        id: "johor-jb04",
        category: "johor-special",
        nameKo: "JB04. 뼈다귀탕",
        nameEn: "Bbyeodagui Tang",
        nameZh: "单人猪骨汤",
        price: "RM 35.00",
        descKo: "부드러운 돼지 목뼈 살코기와 우거지를 넣고 매콤하고 깊은 육수로 끓여낸 1인용 뼈다귀 해장국",
        descEn: "Hearty individual portion of deeply flavorful, spicy pork neck bone soup with vegetables.",
        descZh: "热气腾腾的单人份浓郁香辣猪颈骨汤，配以蔬菜和干白菜",
        image: "assets/menu/jb04.png",
        badge: "Johor Only",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "johor-jb05",
        category: "johor-special",
        nameKo: "JB05. 짬뽕 (밥 또는 면)",
        nameEn: "Jjampong (Rice or Noodle)",
        nameZh: "海鲜炒码面 (辣)",
        price: "RM 28.00",
        descKo: "신선한 해산물과 야채를 센 불에 볶아 불맛을 내고 매콤하고 시원하게 끓여낸 한국식 짬뽕 (밥 또는 면 선택 가능)",
        descEn: "Fiery and refreshing Korean-Chinese style noodle soup loaded with assorted fresh seafood and crisp vegetables.",
        descZh: "新鲜海鲜与爽脆蔬菜猛火爆炒，浇上香辣清爽高汤的韩式海鲜面（可选配米饭或面条）",
        image: "assets/menu/jb05.png",
        badge: "Johor Only",
        serving: "1 Pax",
        spicy: 2
    },

    // --------------------------------------------------------
    // SET MENU
    // --------------------------------------------------------
    {
        id: "set-1",
        category: "set",
        nameKo: "SET1",
        nameEn: "3~4 pax",
        nameZh: "3~4人餐",
        price: "RM 248.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 돼지갈비, 고추장 삼겹살, 김치전골, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Pork Ribs, Chili Sauce Pork Belly, Kimchi Hot Pot, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、排骨、辣酱五花肉、泡菜火锅、蔬菜煎饼",
        image: "assets/menu/set1.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-2",
        category: "set",
        nameKo: "SET2",
        nameEn: "3~4 pax",
        nameZh: "3~4人餐",
        price: "RM 248.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 양념닭갈비, 양념쭈꾸미, 김치전골, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Marinated Chicken, Marinated Spicy Webfoot Octopus, Kimchi Hot Pot, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、调味鸡肉、调味小八爪鱼、泡菜火锅、蔬菜煎饼",
        image: "assets/menu/set2.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-3",
        category: "set",
        nameKo: "SET3",
        nameEn: "2~3 pax",
        nameZh: "2~3人餐",
        price: "RM 138.00",
        descKo: "돼지 스페셜, 삼겹살, 목살, 김치찌개, 부추전",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Kimchi Soup, Chive Pancake",
        descZh: "猪肉特选、五花肉、梅花肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set3.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-4",
        category: "set",
        nameKo: "SET4",
        nameEn: "2~3 pax",
        nameZh: "2~3人餐",
        price: "RM 138.00",
        descKo: "항정살, 돼지갈비, 돼지 주물럭, 김치찌개, 부추전",
        descEn: "Pork Jowls, Pork Ribs, Marinated Pork Special, Kimchi Soup, Chive Pancake",
        descZh: "猪面颊肉、猪排骨、调味特选猪肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set4.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-5",
        category: "set",
        nameKo: "SET5",
        nameEn: "2~3 pax",
        nameZh: "2~3人餐",
        price: "RM 138.00",
        descKo: "돼지 스페셜, 돼지갈비, 닭갈비, 김치찌개, 부추전",
        descEn: "Pork Special, Pork Ribs, Marinated Chicken, Kimchi Soup, Chive Pancake",
        descZh: "猪肉特选、猪排骨、调味鸡肉、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set5.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-6",
        category: "set",
        nameKo: "SET6",
        nameEn: "2~3 pax",
        nameZh: "2~3人餐",
        price: "RM 148.00",
        descKo: "돼지갈비, 매운 닭갈비, 양념쭈꾸미, 김치찌개, 부추전",
        descEn: "Pork Ribs, Spicy Chicken, Spicy Baby Octopus, Kimchi Soup, Chive Pancake",
        descZh: "猪排骨、辣味鸡肉、辣味小八爪鱼、泡菜汤、蔬菜煎饼",
        image: "assets/menu/set6.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 2
    },

    // --------------------------------------------------------
    // BEEF BBQ
    // --------------------------------------------------------
    {
        id: "beef-7",
        category: "beef",
        nameKo: "B01. 갈비본살",
        nameEn: "Galbi Bonsal",
        nameZh: "烤牛排",
        price: "RM 130.00",
        descKo: "양념하지 않은 신선한 갈비본살 숯불구이 (갈비뼈를 제거한 소갈비살)",
        descEn: "Fresh boneless short rib without marinade, charcoal grilled",
        descZh: "无调味新鲜去骨牛小排，炭火烤制",
        image: "assets/menu/galbi_bonsal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-8",
        category: "beef",
        nameKo: "B02. 생갈비",
        nameEn: "Saeng Galbi",
        nameZh: "生牛排",
        price: "RM 130.00",
        descKo: "양념하지 않고 칼집을 내어 구운 전통 생 소갈비구이",
        descEn: "Beef short ribs butterflied or accordion cut, without marinade and char-grilled.",
        descZh: "蝴蝶切或风琴切的无调味小牛排，炭火烤制",
        image: "assets/menu/saeng_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-9",
        category: "beef",
        nameKo: "B03. 왕갈비",
        nameEn: "Wang Galbi",
        nameZh: "特制王牛排",
        price: "RM 130.00",
        descKo: "다오래 한방 특제 간장 양념장에 재워 맛을 낸 손질 소왕갈비",
        descEn: "Beef short rib specially hand filleted marinated with special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的特选纯手工牛小排",
        image: "assets/menu/wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-10",
        category: "beef",
        nameKo: "B04. 우설구이",
        nameEn: "Wooseul Gui",
        nameZh: "烤牛舌",
        price: "RM 90.00",
        descKo: "쫄깃하고 부드러운 맛이 일품인 얇게 썬 최고급 우설구이",
        descEn: "Thinly sliced Ox-tongue grilled over natural charcoal",
        descZh: "薄切牛舌",
        image: "assets/menu/woo_seul_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-11",
        category: "beef",
        nameKo: "B05. 소고기모둠",
        nameEn: "Beef Modum",
        nameZh: "牛肉拼盘",
        price: "RM 320.00",
        descKo: "소고기 4가지 부위 모둠 구성 (우설, 갈비본살, 차돌박이, 갈비살)",
        descEn: "Four kinds of assorted beef BBQ sampler (Ox tongue, boneless short rib, brisket, short rib)",
        descZh: "四种特选牛肉组合（牛舌、去骨牛小排、牛胸肉、牛肋条）",
        image: "assets/menu/beep_modum.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "beef-12",
        category: "beef",
        nameKo: "B06. LA 갈비",
        nameEn: "LA Galbi",
        nameZh: "LA排骨",
        price: "RM 125.00",
        descKo: "뼈째 직각 방향으로 잘라 대파와 마늘을 넣은 특제 간장 양념에 재운 소갈비구이",
        descEn: "Short ribs cut through the bone and marinated in soy sauce, onion, and garlic",
        descZh: "LA排骨是将整条排骨切成与骨头呈直角方向，形成连骨带肉的T骨牛排，主要可做烧烤或炖排骨。",
        image: "assets/menu/la_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-13",
        category: "beef",
        nameKo: "B07. 갈비살주물럭",
        nameEn: "Galbisal",
        nameZh: "去骨牛肋条",
        price: "RM 125.00",
        descKo: "뼈를 바른 갈비살을 즉석에서 특제 마늘 간장 소스로 주물럭 조리한 구이",
        descEn: "Boneless short ribs marinated in garlic-based special sauce",
        descZh: "经大吾来特制酱汁腌制的无骨牛肋条",
        image: "assets/menu/galbi_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-14",
        category: "beef",
        nameKo: "B08. 우삼겹",
        nameEn: "Woosamgyeop",
        nameZh: "牛五花",
        price: "RM 80.00",
        descKo: "부드럽고 지방이 풍부한 양념하지 않은 차돌 우삼겹살 구이",
        descEn: "Thinly sliced, richly marbled beef without marinade",
        descZh: "无调味薄切雪花肥牛",
        image: "assets/menu/woo_samgyeop.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },

    // --------------------------------------------------------
    // PORK BBQ
    // --------------------------------------------------------
    {
        id: "pork-15",
        category: "pork",
        nameKo: "P01. 돼지스페셜",
        nameEn: "Pork Special",
        nameZh: "猪面颊肉",
        price: "RM 45.00",
        descKo: "돼지 머리에서 얻은 부드럽고 쫄깃한 식감의 특수 부위 (덜미살)",
        descEn: "Specially selected cuts of pork that is soft and tender",
        descZh: "严选软嫩猪面颊肉",
        image: "assets/menu/dwaeji_special.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-16",
        category: "pork",
        nameKo: "P02. 항정살",
        nameEn: "Hangjungsal",
        nameZh: "烤松坂猪肉",
        price: "RM 45.00",
        descKo: "천겹살이라 불리는 돼지 목덜미의 쫄깃하고 마블링이 우수한 항정살 구이",
        descEn: "Pork Jowls grilled over natural charcoal",
        descZh: "烤松坂猪肉，俗称猪颈肉，因其大理石般的美丽纹理和Q弹口感而闻名",
        image: "assets/menu/hang_jung_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-17",
        category: "pork",
        nameKo: "P03. 목살",
        nameEn: "Moksal",
        nameZh: "梅花肉",
        price: "RM 38.00",
        descKo: "기름기가 적고 담백하여 숯불구이에 가장 적합한 신선한 목살 목등심",
        descEn: "Pork Shoulder cut into thick slices and grilled over charcoal",
        descZh: "炭烤新鲜猪梅花肉（肩胛肉），油脂较少，肉质紧实多汁",
        image: "assets/menu/mok_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-18",
        category: "pork",
        nameKo: "P04. 삼겹살",
        nameEn: "Samgyeopsal",
        nameZh: "烤五花肉",
        price: "RM 38.00",
        descKo: "살코기와 지방이 세 겹으로 되어 있어 부드럽고 고소한 삼겹살 구이",
        descEn: "Pork Belly grilled and dipped in salt or ssamjang (red soybean paste dip)",
        descZh: "五花肉是猪肚腩部位的肉，因瘦肉 and 脂肪交替，所以肉质软嫩可口。一般是生肉直接上火烤",
        image: "assets/menu/samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-19",
        category: "pork",
        nameKo: "P05. 고추장 삼겹살",
        nameEn: "Gochujang Samgyeopsal",
        nameZh: "辣椒酱烤五花肉",
        price: "RM 42.00",
        descKo: "삼겹살에 매콤달콤한 고추장 양념을 버무려 숯불 향을 입힌 양념구이",
        descEn: "Pork belly marinated in spicy Korean chili paste",
        descZh: "将五花肉用辣椒酱做成的调味酱搅拌后，烤着吃或炒着吃即可。用辣椒酱调味的五花肉肥而不腻，非常香嫩。",
        image: "assets/menu/gochujang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-20",
        category: "pork",
        nameKo: "P06. 양념 돼지갈비",
        nameEn: "Yangnyeom Dwaeji Galbi",
        nameZh: "调味猪排骨",
        price: "RM 42.00",
        descKo: "돼지갈비대를 특제 간장 양념장에 재워 육즙이 가득하고 감칠맛 나는 구이",
        descEn: "Pork marinated in soy sauce, garlic, and sweet onion marinade",
        descZh: "将猪排肉用调味汁腌渍以后放到炭 火上烤熟即可。",
        image: "assets/menu/yangnyeom_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-21",
        category: "pork",
        nameKo: "P07. 한방 돼지왕갈비",
        nameEn: "Hanbang Dwaeji Wang Galbi",
        nameZh: "韩方调味大猪排",
        price: "RM 48.00",
        descKo: "개성있는 칼집을 낸 큼직한 돼지갈비를 엄선된 인삼, 약초 추출물과 특제 간장에 잰 건강 구이",
        descEn: "Pork ribs marinated in Korean ginseng, herb extracts, and soy sauce",
        descZh: "经秘制人参、韩方草本提取物及大吾来特制酱汁腌制的特选大猪排",
        image: "assets/menu/hanbang_dwaeji_wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-22",
        category: "pork",
        nameKo: "P08. 돼지 주물럭",
        nameEn: "Dwaeji Jumulluk",
        nameZh: "调味猪肋条",
        price: "RM 47.00",
        descKo: "엄선한 돼지고기 살코기를 즉석에서 마늘과 달콤한 다오래 간장 소스에 조리한 주물럭",
        descEn: "Selected cuts of soft pork marinated in special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的软嫩猪肋条肉",
        image: "assets/menu/dwaeji_jumulluk.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-23",
        category: "pork",
        nameKo: "P09. 매운 돼지갈비",
        nameEn: "Maeun Dwaeji Galbi",
        nameZh: "辣味猪排骨",
        price: "RM 42.00",
        descKo: "수제 손질한 엄선된 돼지고기를 매콤한 한국식 고추장 양념장에 재운 구이",
        descEn: "Pork marinated in spicy Korean chili sauce and soy sauce",
        descZh: "经韩式辣酱腌制的纯手工特选辣猪排",
        image: "assets/menu/maeun_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-24",
        category: "pork",
        nameKo: "P10. 한방 삼겹살",
        nameEn: "Hanbang Samgyeopsal",
        nameZh: "韩方五花肉",
        price: "RM 45.00",
        descKo: "신선한 삼겹살에 특제 인삼 및 몸에 좋은 한방 약초 추출물을 입혀 숙성시킨 삼겹살 구이",
        descEn: "Slices of pork belly marinated in special Korean ginseng and herbs extract",
        descZh: "经秘制人参及韩方草本提取物腌制的切片五花肉",
        image: "assets/menu/hanbang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },

    // --------------------------------------------------------
    // OTHER BBQ
    // --------------------------------------------------------
    {
        id: "other-bbq-25",
        category: "other-bbq",
        nameKo: "M01. 양념 닭갈비",
        nameEn: "Yangnyeom Dakgalbi",
        nameZh: "辣酱烤鸡肉",
        price: "RM 38.00",
        descKo: "부드러운 닭다리살을 고추장 양념장에 재웠다가 숯불에 구워 먹는 강원도 춘천식 별미 요리",
        descEn: "Chicken marinated in Daorae sauce and cooked on a charcoal grill",
        descZh: "鸡肉用辣椒酱调制的调味酱腌一会儿，入味后放在炭火上烤熟即可",
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-26",
        category: "other-bbq",
        nameKo: "M02. 닭갈비",
        nameEn: "Dak Galbi",
        nameZh: "辣调味鸡胸肉",
        price: "RM 38.00",
        descKo: "지방이 적고 담백한 닭가슴살 및 닭정육 부위를 청양 고춧가루 특제 매운 양념에 재운 요리",
        descEn: "Lean skinless chicken fillets marinated in our hot chili sauce",
        descZh: "辣味调酱腌制的去皮去骨无脂鸡胸肉",
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-27",
        category: "other-bbq",
        nameKo: "M03. 양념 양고기",
        nameEn: "Yangnyeom Yanggogi",
        nameZh: "调味烤羊肉",
        price: "RM 52.00",
        descKo: "엄선한 고급 양고기 살코기를 수제 손질하여 다오래 특제 갈비 소스에 버무려 구운 양고기",
        descEn: "Chosen cuts of lamb specially hand filleted, marinated in special Daorae sauce",
        descZh: "经大吾来特制酱汁腌制的特选纯手工羊肉",
        image: "assets/menu/yangnyeom_yanggogi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "other-bbq-28",
        category: "other-bbq",
        nameKo: "M04. 양념 오징어구이",
        nameEn: "Yangnyeom Ojingeo Gui",
        nameZh: "辣烤鱿鱼",
        price: "RM 57.00",
        descKo: "신선하고 통통한 오징어에 칼집을 내어 다오래 특제 고추장 매운 소스를 곁들여 석쇠에 구운 요리",
        descEn: "Fresh squid carved and prepared in our hot chili sauce",
        descZh: "经特制辣酱调味烤制的新鲜鱿鱼",
        image: "assets/menu/yangnyeom_ojingeo_gui.png",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "other-bbq-29",
        category: "other-bbq",
        nameKo: "M05. 양념 쭈꾸미구이",
        nameEn: "Yangnyeom Jukkumi Gui",
        nameZh: "辣烤小八爪鱼",
        price: "RM 57.00",
        descKo: "신선한 쭈꾸미를 손질해 불 맛 가득한 다오래 고추장 특제 매운 양념 소스에 맛있게 구운 요리",
        descEn: "Fresh baby octopus carved and prepared in our hot chili sauce",
        descZh: "经特制辣酱调味烤制的新鲜小八爪鱼",
        image: "assets/menu/jjuggumi_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 3
    },
    {
        id: "other-bbq-29-b",
        category: "other-bbq",
        nameKo: "M06. 장어구이",
        nameEn: "Jangeo Gui (Salt / Soy Sauce)",
        nameZh: "烤鳗鱼",
        price: "1pc RM 125 / 2pcs RM 235",
        descKo: "소금구이 또는 간장 양념구이로 선택 가능한 신선한 보양 민물장어 구이",
        descEn: "Grilled freshwater eel served with choice of salt or soy sauce glaze.",
        descZh: "新鲜淡水烤鳗鱼，可选盐烤或酱油烤，富含多种营养，是大补之品",
        image: "assets/menu/jangeo_gui.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },

    // --------------------------------------------------------
    // STEWS
    // --------------------------------------------------------
    {
        id: "stew-30",
        category: "stew",
        nameKo: "S01. 김치찌개",
        nameEn: "Kimchi Jjigae",
        nameZh: "猪肉泡菜汤",
        price: "RM 28.00",
        descKo: "푹 익은 신김치에 부드러운 돼지고기, 고소한 두부, 대파를 듬뿍 넣어 얼큰하고 깊은 맛을 낸 한국인의 소울푸드",
        descEn: "Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean soul food.",
        descZh: "将酸泡菜放入锅中，再加入猪肉、豆腐以及切成粗丝的葱等材料炖煮即可。",
        image: "assets/menu/kimchi_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-31",
        category: "stew",
        nameKo: "S02. 된장찌개",
        nameEn: "Doenjang Jjigae",
        nameZh: "海鲜大酱汤",
        price: "RM 30.00",
        descKo: "멸치 육수에 구수한 재래식 된장을 풀고 신선한 조개류, 두부, 애호박을 넣어 끓인 밥도둑 찌개",
        descEn: "Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash.",
        descZh: "高汤中放入大酱，再加入肉、鱼贝类、豆腐、西葫芦等熬煮即可。",
        image: "assets/menu/doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-32",
        category: "stew",
        nameKo: "S03. 순두부찌개",
        nameEn: "Sundubu Jjigae",
        nameZh: "猪肉嫩豆腐锅",
        price: "RM 28.00",
        descKo: "몽글몽글한 순두부와 다진 돼지고기, 신선한 야채를 넣고 얼큰한 고추기름 육수로 맛을 낸 찌개 (날달걀 추가 가능)",
        descEn: "Soft bean curd stew boiled with minced pork and vegetables in a spicy red chili broth.",
        descZh: "在砂锅中放入嫩豆腐和猪肉、蔬菜，再加入辣高汤, 顶上面打入新鲜鸡蛋",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-33",
        category: "stew",
        nameKo: "S04. 해물순두부찌개",
        nameEn: "Haemul Sundubu Jjigae",
        nameZh: "海鲜嫩豆腐锅",
        price: "RM 28.00",
        descKo: "부드러운 순두부에 신선한 게, 새우, 조개류 등 모듬 해물을 듬뿍 넣어 바다의 시원하고 얼큰한 맛을 살린 찌개",
        descEn: "Soft bean curd stew boiled with assorted seafood (shrimps, clams) in a spicy, flavorful broth.",
        descZh: "在砂锅中放入嫩豆腐和虾、蛤蜊等海鲜，再加入高汤熬煮而成，吃起来十分爽口",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-34",
        category: "stew",
        nameKo: "S05. 보스된장찌개",
        nameEn: "Boss Doenjang Jjigae",
        nameZh: "牛肉大酱汤",
        price: "RM 30.00",
        descKo: "진하게 끓인 전통 한식 된장 육수에 부드러운 차돌박이 소고기, 두부, 야채를 아낌없이 넣은 프리미엄 된장찌개",
        descEn: "Tofu and fresh vegetables in a rich traditional Korean bean broth topped with beef, served with rice.",
        descZh: "在传统的韩式浓郁大酱汤中加入牛肉、豆腐和新鲜蔬菜熬制的大酱汤",
        image: "assets/menu/boss_doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-34-b",
        category: "stew",
        nameKo: "S06. 소불고기",
        nameEn: "So Bulgogi",
        nameZh: "砂锅牛肉",
        price: "RM 45.00",
        descKo: "달콤한 특제 간장 양념에 버무린 소고기 불고기와 당면, 야채를 자작하게 끓여낸 찌개",
        descEn: "Thinly sliced beef marinated in sweet soy sauce with glass noodles and vegetables.",
        descZh: "在甜沙参酱汁中腌制的切片牛肉，配以粉条和各种蔬菜同煮",
        image: "assets/menu/so_bulgogi.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-34-c",
        category: "stew",
        nameKo: "S07. 돼지불고기",
        nameEn: "Dwaeji Bulgogi",
        nameZh: "砂锅猪肉",
        price: "RM 40.00",
        descKo: "특제 양념에 재운 부드러운 돼지불고기와 신선한 버섯, 당면, 야채를 버무린 찌개",
        descEn: "Tender pork marinated in sweet soy sauce with mushrooms and vegetables.",
        descZh: "腌制好的软嫩猪肉与新鲜蘑菇、粉条和蔬菜同煮，汤汁极佳",
        image: "assets/menu/dwaeji_bulgogi.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-35",
        category: "stew",
        nameKo: "S08. 갈비탕",
        nameEn: "Galbitang",
        nameZh: "牛排骨汤",
        price: "RM 40.00",
        descKo: "핏물을 뺀 소갈비와 큼직한 무를 가마솥에서 푹 고아 맑고 시원한 육수가 일품인 대표 보양식 갈비탕",
        descEn: "Beef ribs and white radish chunks simmered together until tender. The clear stock is rich and savory.",
        descZh: "用牛排骨熬的汤，牛排骨浸泡去血后与萝卜一起熬煮至肉烂，不但汤汁香醇",
        image: "assets/menu/galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-36",
        category: "stew",
        nameKo: "S09. 우거지갈비탕",
        nameEn: "Ugeoji Galbitang",
        nameZh: "干白菜排骨汤",
        price: "RM 40.00",
        descKo: "소갈비를 끓여낸 육수에 구수한 시골 된장과 식이섬유가 풍부한 우거지를 푹 끓여내어 위장에 좋은 건강 탕",
        descEn: "Napa cabbage leaves slowly simmered in a beef rib stock and seasoned with traditional doenjang (soybean paste).",
        descZh: "用排骨长时间熬煮制成高汤，再放入泡发的干白菜和大酱熬煮。",
        image: "assets/menu/ugeoji_galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-37",
        category: "stew",
        nameKo: "S10. 육개장",
        nameEn: "Yukgaejang",
        nameZh: "香辣牛肉汤",
        price: "RM 38.00",
        descKo: "소 양지머리를 고아 고사리, 대파, 토란대 등의 나물을 넣고 붉은 고추기름으로 맵고 얼큰하게 양념한 보양식",
        descEn: "A spicy soup made of shredded beef brisket, radish, green onions, bean sprouts, and fiddleheads.",
        descZh: "用牛的排骨 and 萝卜等长时间熬煮，再加入大葱、青芋茎、蕨菜 and 辣椒粉等调味而成。",
        image: "assets/menu/yukgaejang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 2
    },

    // --------------------------------------------------------
    // HOT POTS
    // --------------------------------------------------------
    {
        id: "hotpot-j01",
        category: "hotpot",
        nameKo: "J01. 김치전골",
        nameEn: "Kimchi Jeongol",
        nameZh: "泡菜火锅",
        price: "S: RM 80 / L: RM 95",
        descKo: "신선한 돼지고기, 두부, 가래떡, 라면사리 등을 넣어 여럿이서 푸짐하게 즐기는 매콤한 김치전골",
        descEn: "Spicy hot pot with kimchi, pork, tofu, rice cake, and ramen noodles.",
        descZh: "放入泡菜、猪肉、豆腐、年糕和拉面同煮的经典韩式泡菜火锅",
        image: "assets/menu/kimchi_jeongol.avif",
        badge: "",
        serving: "2-4 Pax",
        spicy: 1
    },
    {
        id: "hotpot-j02",
        category: "hotpot",
        nameKo: "J02. 부대전골",
        nameEn: "Budae Jeongol",
        nameZh: "部队火锅",
        price: "RM 95.00",
        descKo: "햄, 소시지, 베이크드 빈스, 라면사리 등을 듬뿍 넣어 얼큰하고 진한 육수의 의정부식 부대전골",
        descEn: "Spicy sausage and ham hot pot with baked beans, vegetables, and ramen noodles.",
        descZh: "放入多种香肠、火腿、芝士、洋葱和拉面同煮的香辣韩式部队火锅",
        image: "assets/menu/budae_jeongol.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 1
    },
    {
        id: "hotpot-j03",
        category: "hotpot",
        nameKo: "J03. 불낙전골",
        nameEn: "Bulnak Jeongol",
        nameZh: "牛肉章鱼火锅",
        price: "RM 100.00",
        descKo: "부드러운 소고기와 쫄깃한 낙지, 신선한 야채가 조화를 이루는 영양 만점의 매콤한 불낙전골",
        descEn: "Spicy and nourishing combination of beef, small octopus, and fresh mushrooms.",
        descZh: "牛肉与整只章鱼同煮的经典高能海陆双拼辣味火锅，营养丰富",
        image: "assets/menu/bulnak_jeongol.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 1
    },
    {
        id: "hotpot-j04",
        category: "hotpot",
        nameKo: "J04. 김치찜",
        nameEn: "Kimchi Jjim",
        nameZh: "泡菜炖猪肉",
        price: "RM 130.00",
        descKo: "묵은지와 도톰한 돼지 삼겹살, 갈비를 가마솥에 장시간 푹 쪄내어 입에서 녹는 전통 김치찜",
        descEn: "Slow cooked aged kimchi stew with tender pork belly and ribs (30 min cooking time).",
        descZh: "酸爽的老熟泡菜与厚切猪五花肉和排骨慢火炖制，猪肉入口即化",
        image: "assets/menu/kimchi_jjim.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 1
    },
    {
        id: "hotpot-j05",
        category: "hotpot",
        nameKo: "J05. 버섯불고기전골",
        nameEn: "Beoseot Bulgogi Jeongol",
        nameZh: "蘑菇牛肉火锅",
        price: "RM 98.00",
        descKo: "다양한 종류의 신선한 버섯과 달콤한 소불고기, 당면을 맑은 육수에 보글보글 끓인 담백한 전골",
        descEn: "Sweet soy sauce-based beef stew cooked with assorted fresh mushrooms and glass noodles.",
        descZh: "各种新鲜蘑菇与韩式烤牛肉、粉条一起在清汤中熬煮，味道鲜甜清淡",
        image: "assets/menu/beoseot_bulgogi_jeongol.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "hotpot-j06",
        category: "hotpot",
        nameKo: "J06. 돼지불고기전골",
        nameEn: "Dwaeji Bulgogi Jeongol",
        nameZh: "猪肉火锅",
        price: "RM 80.00",
        descKo: "부드러운 돼지 주물럭과 야채, 당면을 달콤한 특제 육수에 넣어 깔끔하게 끓인 전골 요리",
        descEn: "Sweet soy sauce-based pork stew cooked with vegetables and glass noodles.",
        descZh: "调味猪肉与新鲜蘑菇、粉条和各类蔬菜在清汤中熬煮的温润火锅",
        image: "assets/menu/dwaeji_bulgogi_jeongol.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "hotpot-j07",
        category: "hotpot",
        nameKo: "J07. 갈비찜",
        nameEn: "Galbi Jjim",
        nameZh: "炖排骨",
        price: "RM 90.00",
        descKo: "소갈비를 간장 소스에 밤, 은행, 대추, 무 등과 함께 달콤하게 조려낸 명절 대표 요리 갈비찜",
        descEn: "Braised beef short ribs simmered in a sweet soy sauce with chestnuts and dates.",
        descZh: "精选牛排骨与栗子、大枣等配料在甜酱油汁中慢火炖制的韩式招牌炖牛排",
        image: "assets/menu/galbi_jjim.avif",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "hotpot-j08",
        category: "hotpot",
        nameKo: "J08. 삼계탕",
        nameEn: "Samgyetang",
        nameZh: "参鸡汤",
        price: "RM 50.00",
        descKo: "어린 닭의 뱃속에 인삼, 찹쌀, 마늘, 대추를 넣고 푹 끓여낸 여름철 최고의 전통 보양 약선탕",
        descEn: "Whole spring chicken stuffed with Korean ginseng, dates, garlic, and sticky rice.",
        descZh: "整只童子鸡内部填满高丽参、糯米、大蒜和大枣慢火熬制的传统韩国第一补汤",
        image: "assets/menu/samgyetang.avif",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },

    // --------------------------------------------------------
    // RICE DISHES
    // --------------------------------------------------------
    {
        id: "rice-45",
        category: "rice",
        nameKo: "R01. 돌솥비빔밥",
        nameEn: "Dolsot Bibimbap",
        nameZh: "石锅拌饭",
        price: "RM 30.00",
        descKo: "뜨거운 돌솥에 밥과 신선한 오색 나물, 볶은 소고기, 계란 노른자를 올려 고추장에 비벼 먹는 한식 대표 비빔밥",
        descEn: "Bibimbap served in a sizzling hot stone pot. The crispy rice at the bottom, mixed with various toppings and gochujang.",
        descZh: "在加热의石锅中分别放入米饭、各种素菜和炒肉丝，用辣椒酱或酱油搅拌即可。",
        image: "assets/menu/dolsot_bibimbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-46",
        category: "rice",
        nameKo: "R03. 소불고기볶음밥",
        nameEn: "Beef Bulgogi Bokkeumbap",
        nameZh: "牛肉烤肉炒饭",
        price: "RM 26.00",
        descKo: "부드럽고 짭조름한 소불고기와 야채를 밥과 함께 철판에서 고소하게 볶아낸 소불고기 볶음밥",
        descEn: "Stir-fried rice with tender, savory beef bulgogi and fresh vegetables.",
        descZh: "香浓烤牛肉与大米饭和蔬菜在铁板上炒制的美味烤肉炒饭",
        image: "assets/menu/beep_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-47",
        category: "rice",
        nameKo: "R04. 돼지불고기볶음밥",
        nameEn: "Dwaeji Bulgogi Bokkeumbap",
        nameZh: "辣炒猪肉炒饭",
        price: "RM 26.00",
        descKo: "매콤달콤한 고추장 돼지불고기 소스로 밥과 야채를 맛있게 불 맛나게 볶아낸 볶음밥",
        descEn: "Stir-fried rice with sweet and spicy pork bulgogi and assorted vegetables.",
        descZh: "韩式辣炒猪肉与米饭及铁板一起炒制的高感度猪肉炒饭",
        image: "assets/menu/dwaeji_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-48",
        category: "rice",
        nameKo: "R05. 김치볶음밥",
        nameEn: "Kimchi Bokkeumbap",
        nameZh: "泡菜炒饭",
        price: "RM 26.00",
        descKo: "신김치와 베이컨 또는 고기를 볶은 뒤 참기름을 두른 볶음밥 위에 바삭한 계란후라이를 얹은 요리",
        descEn: "Kimchi fried rice with meat, topped with a fried egg and seaweed flakes.",
        descZh: "泡菜和米饭炒制，并配以煎蛋的泡菜炒饭",
        image: "assets/menu/kimchi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-49",
        category: "rice",
        nameKo: "R06. 잡채볶음밥",
        nameEn: "Japchae Bokkeumbap",
        nameZh: "杂菜炒饭",
        price: "RM 26.00",
        descKo: "한식 잔치 요리인 당면 잡채와 밥을 함께 센 불에 볶아낸 쫄깃하고 고소한 잡채 볶음밥",
        descEn: "Korean glass noodle (Japchae) and rice pan fried with assorted seasoned vegetables.",
        descZh: "韩式杂菜（红薯淀粉粉丝）与各类调味蔬菜 and 米饭同炒的杂菜炒饭",
        image: "assets/menu/japchae_bokkeumbap.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-50",
        category: "rice",
        nameKo: "R07. 주먹밥",
        nameEn: "Jumeokbap",
        nameZh: "手抓饭团",
        price: "RM 20.00",
        descKo: "따뜻한 밥에 고소한 참기름, 통깨, 조미 김가루를 조물조물 버무려 한 입 크기로 동글동글하게 뭉친 주먹밥",
        descEn: "Hand-rolled rice balls seasoned with fragrant sesame oil, sesame seeds, and seaweed flakes.",
        descZh: "拌入海苔碎和蔬菜手工捏成的圆形饭团",
        image: "assets/menu/jumeokbap.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "rice-51",
        category: "rice",
        nameKo: "R08. 공기밥",
        nameEn: "Bap",
        nameZh: "白米饭",
        price: "RM 6.00",
        descKo: "매장에서 매일 신선하게 지은 고슬고슬하고 찰진 흰 쌀밥 공기밥",
        descEn: "Freshly steamed white sticky rice bowl.",
        descZh: "白米饭",
        image: "assets/menu/bap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },

    // --------------------------------------------------------
    // NOODLES
    // --------------------------------------------------------
    {
        id: "noodle-n01",
        category: "noodle",
        nameKo: "N01. 매운야채비빔국수",
        nameEn: "Maeun Yachae Bibim Guksu",
        nameZh: "辣味蔬菜拌面",
        price: "RM 28.00",
        descKo: "탄력 있는 소면에 신선한 야채와 대파, 그리고 특제 고추장 매운 소스를 얹어 새콤달콤하게 비빈 별미 국수",
        descEn: "Chilled noodles mixed with fresh crisp vegetables in an extremely spicy red pepper sauce.",
        descZh: "冰爽的小麦细面配以新鲜脆嫩蔬菜，并淋上特制极辣辣酱，爽口开胃",
        image: "assets/menu/maeun_yachae_bibimguksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 3
    },
    {
        id: "noodle-n02",
        category: "noodle",
        nameKo: "N02. 짜장면",
        nameEn: "Jajangmyeon",
        nameZh: "炸酱面",
        price: "RM 28.00",
        descKo: "춘장을 기름에 볶아 돼지고기와 감자, 양파 등의 채소를 듬뿍 넣고 전분물로 걸쭉하게 소스를 얹어 비벼 먹는 면 요리",
        descEn: "Noodles topped with a thick, rich sauce made of chunjang (black bean paste), diced pork, and vegetables.",
        descZh: "劲道的面条淋上由黑豆酱（春酱）、猪肉碎和洋葱丁炒制的浓郁黑色炸酱的韩式中华炸酱面",
        image: "assets/menu/jajangmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-52",
        category: "noodle",
        nameKo: "N03. 물냉면",
        nameEn: "Mul Naengmyeon",
        nameZh: "水冷面",
        price: "RM 28.00",
        descKo: "메밀 면을 삶아 동치미 국물과 소고기 육수 섞은 국물에 차갑게 말아 먹는 음식이다. 무, 배, 등을 얹고 겨자와 식초로 양념한다.",
        descEn: "Buckwheat noodles served in chilled soup made of dongchimi (radish kimchi) liquid and beef broth.",
        descZh: "用白萝卜泡菜汤汁和牛肉高汤调成冰镇汤汁，放入煮熟的荞麦面，再加入一些萝卜、梨等装饰配菜",
        image: "assets/menu/mul_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-53",
        category: "noodle",
        nameKo: "N04. 비빔냉면",
        nameEn: "Bibim Naengmyeon",
        nameZh: "拌冷面",
        price: "RM 28.00",
        descKo: "메밀로 만든 면을 삶아 찬물에 헹궈 물기를 뺀 다음 소고기 편육이나 홍어회무침, 무, 오이, 삶은 계란 등을 얹고 고추장 양념장에 비벼 차갑게 먹는 음식이다.",
        descEn: "Chilled buckwheat noodles garnished with cold slices of beef, skate, and radish or cucumber. Served with a spicy gochujang mixing sauce.",
        descZh: "拌冷面多使用荞麦面。荞麦面煮熟后用凉水冲洗并沥干水分，然后放入白切牛肉片",
        image: "assets/menu/bibim_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-54",
        category: "noodle",
        nameKo: "N05. 김치비빔국수",
        nameEn: "Kimchi Bibim Guksu",
        nameZh: "泡菜拌面",
        price: "RM 28.00",
        descKo: "새콤하게 익은 김치를 썰어 넣고 고추장, 참기름으로 비벼 낸 매콤 새콤한 한국 전통 비빔국수",
        descEn: "Chilled wheat noodles tossed in a sweet, sour, and spicy chili sauce topped with chopped Kimchi.",
        descZh: "配以辣泡菜的冰凉辣拌面",
        image: "assets/menu/image_5d08b9_3.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-55",
        category: "noodle",
        nameKo: "N06. 김치말이국수",
        nameEn: "Kimchimari Guksu",
        nameZh: "泡菜汤面",
        price: "RM 28.00",
        descKo: "동치밋국이나 열무 김칫국 또는 김칫국을 섞은 육수에 삶아 낸 국수를 넣어 시원하게 먹는 음식이다.",
        descEn: "This is a noodle dish made with chilled dongchimi soup or kimchi soup mixed with beef stock and topped with beef.",
        descZh: "用水萝卜泡菜或萝卜缨泡菜、泡菜等的汤汁调和高汤备用，面条煮熟后放入冰镇的高汤",
        image: "assets/menu/kimchi_mari_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-56",
        category: "noodle",
        nameKo: "N07. 잔치국수",
        nameEn: "Janchi Guksu",
        nameZh: "喜面",
        price: "RM 28.00",
        descKo: "삶은 국수에 계란지단 등으로 고명을 얹고 멸치장국을 부어낸 국수로 예로부터 잔치 때 손님을 대접하는 대표 음식이다.",
        descEn: "Thin wheat noodles served in a hot, clear anchovy broth with egg, zucchini, and seaweed garnish.",
        descZh: "在煮熟的面条上放鸡蛋丝等菜码，再浇上鳀鱼汤汁而成。自古用来在婚宴、生日宴招待宾客。",
        image: "assets/menu/janchi_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-57",
        category: "noodle",
        nameKo: "N08. 라면",
        nameEn: "Ramyeon",
        nameZh: "韩式方便拉面",
        price: "RM 23.00",
        descKo: "양은 냄비에 끓여 낸 얼큰하고 꼬들꼬들한 한국식 인스턴트 매운 라면 (계란 및 파 송송 포함)",
        descEn: "Spicy and savory Korean instant noodle cooked in a hot brass pot with eggs and green onion.",
        descZh: "香辣浓郁的韩式即食方便拉面",
        image: "assets/menu/ramyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },

    // --------------------------------------------------------
    // OTHER CUISINE (ACTUAL SIDE DISHES FROM PDF)
    // --------------------------------------------------------
    {
        id: "side-c01",
        category: "other-cuisine",
        nameKo: "C01. 찜닭",
        nameEn: "Jjimdak",
        nameZh: "安东炖鸡",
        price: "RM 80.00",
        descKo: "닭고기와 감자, 당면을 매콤하고 짭조름한 간장 양념에 졸여 만든 경상북도 안동의 향토 요리",
        descEn: "Simmered chicken with potatoes and glass noodles in a savory, slightly spicy soy sauce.",
        descZh: "鸡肉块、土豆、胡萝卜和粉条在浓郁的甜辣酱油汁中炖制的韩式传统安东炖鸡",
        image: "assets/menu/jjimdak.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 1
    },
    {
        id: "side-c02",
        category: "other-cuisine",
        nameKo: "C02. 오삼불고기",
        nameEn: "Osam Bulgogi",
        nameZh: "鱿鱼炒猪肉",
        price: "RM 90.00",
        descKo: "쫄깃한 오징어와 고소한 돼지 삼겹살을 매콤한 고추장 양념에 볶아낸 최고의 콤비네이션 요리",
        descEn: "Stir-fried pork belly and squid marinated in a spicy Korean chili paste.",
        descZh: "Q弹鱿鱼与香浓五花肉在韩式辣椒酱中同炒的经典鱿鱼五花肉双拼",
        image: "assets/menu/osam_bulgogi.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 2
    },
    {
        id: "side-c03",
        category: "other-cuisine",
        nameKo: "C03. 낙지볶음",
        nameEn: "Nakji Bokkeum",
        nameZh: "辣炒章鱼",
        price: "RM 68.00",
        descKo: "피로 회복에 좋은 신선한 낙지를 매콤한 고추장 양념에 센 불로 불맛 나게 볶아낸 별미 요리",
        descEn: "Small octopus stir-fried in a fiery, spicy Korean chili sauce with vegetables.",
        descZh: "新鲜的小章鱼配以洋葱在极辣的韩式辣酱中猛火爆炒，口感脆嫩鲜辣",
        image: "assets/menu/nakji_bokkeum.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 3
    },
    {
        id: "side-c04",
        category: "other-cuisine",
        nameKo: "C04. 오징어소면",
        nameEn: "Ojingeo Somyeon",
        nameZh: "辣炒鱿鱼配素面",
        price: "RM 68.00",
        descKo: "매콤하게 볶아낸 오징어볶음에 잘 삶아진 소면을 비벼 먹는 안주로도 훌륭한 요리",
        descEn: "Stir-fried squid in a spicy Korean chili sauce served with boiled wheat noodles.",
        descZh: "香辣可口的辣炒鱿鱼配以水煮小麦细面，是极佳的下酒菜和下饭菜",
        image: "assets/menu/ojingeo_somyeon.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 2
    },
    {
        id: "side-c05",
        category: "other-cuisine",
        nameKo: "C05. 제육볶음",
        nameEn: "Jeyuk Bokkeum",
        nameZh: "辣炒猪肉",
        price: "RM 60.00",
        descKo: "도톰한 돼지 앞다리살 또는 오겹살을 대파, 양파와 함께 매콤한 특제 고추장 소스에 철판에서 볶아낸 요리",
        descEn: "Stir-fried sliced pork belly and vegetables in a spicy Korean chili paste.",
        descZh: "切片五花肉与新鲜蔬菜在韩式辣椒酱中铁板翻炒而成的辣炒猪肉",
        image: "assets/menu/jeyuk_bokkeum.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 2
    },
    {
        id: "side-c06",
        category: "other-cuisine",
        nameKo: "C06. 김치전",
        nameEn: "Kimchi Jeon",
        nameZh: "泡菜煎饼",
        price: "RM 35.00",
        descKo: "잘 익은 신김치를 송송 썰어 밀가루 반죽에 섞어 기름을 두르고 노릇하고 바삭하게 구워낸 전",
        descEn: "Savory pancake made with finely chopped sour kimchi and vegetables, pan-fried to crispy perfection.",
        descZh: "将酸熟泡菜切碎拌入面糊中，在煎锅中煎至金黄酥脆的经典韩国泡菜饼",
        image: "assets/menu/kimchi_jeon.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 1
    },
    {
        id: "side-c07",
        category: "other-cuisine",
        nameKo: "C07. 해물파전",
        nameEn: "Haemul Pajeon",
        nameZh: "海鲜葱饼",
        price: "RM 45.00",
        descKo: "향긋한 쪽파와 오징어, 새우, 조개 등 모듬 해물을 아낌없이 넣어 두툼하고 고소하게 지진 해물전",
        descEn: "Savory Korean pancake packed with green onions and assorted seafood, pan-fried.",
        descZh: "加入大量香葱和鱿鱼、虾仁等海鲜面糊煎制的厚实香浓海鲜葱饼",
        image: "assets/menu/haemul_pajeon.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "side-c08",
        category: "other-cuisine",
        nameKo: "C08. 부추전",
        nameEn: "Buchu Jeon",
        nameZh: "韭菜煎饼",
        price: "RM 35.00",
        descKo: "몸에 좋은 신선한 영양 부추를 가득 썰어 반죽해 고소하고 얇게 구워낸 바삭한 부추전",
        descEn: "Crispy, savory pancake made with fresh green chives and chili peppers.",
        descZh: "加入新鲜健康韭菜糊煎制的薄脆韭菜饼",
        image: "assets/menu/buchu_jeon.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "side-c09",
        category: "other-cuisine",
        nameKo: "C09. 떡볶이",
        nameEn: "Tteokbokki",
        nameZh: "辣炒年糕",
        price: "RM 38.00",
        descKo: "말랑한 쌀떡과 사각 어묵, 양배추를 매콤달콤한 고추장 베이스 소스에 조려낸 한국 대표 길거리 음식",
        descEn: "Chewy rice cakes and fish cakes simmered in a sweet and spicy red chili sauce.",
        descZh: "软糯年糕条与鱼饼、卷心菜一起在特制甜辣酱中熬煮的韩国第一街头小吃",
        image: "assets/menu/tteokbokki.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 1
    },
    {
        id: "side-c10",
        category: "other-cuisine",
        nameKo: "C10. 잡채",
        nameEn: "Japchae",
        nameZh: "韩式杂菜",
        price: "RM 40.00",
        descKo: "삶은 당면에 시금치, 당근, 버섯, 양파, 소고기 등의 오색 고명을 얹고 참기름과 간장 양념으로 버무린 요리",
        descEn: "Korean sweet potato glass noodles stir-fried with colorful vegetables, mushrooms, and beef.",
        descZh: "红薯淀粉粉丝与菠菜、胡萝卜、蘑菇和牛肉丝一起淋上香油和酱油翻炒的杂菜",
        image: "assets/menu/japchae.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "side-c11",
        category: "other-cuisine",
        nameKo: "C11. 보쌈",
        nameEn: "Bossam",
        nameZh: "白切肉",
        price: "RM 65.00",
        descKo: "돼지 오겹살을 한방 재료와 삶아내어 매콤한 보쌈김치, 무속과 함께 상추에 싸 먹는 수육 요리",
        descEn: "Tender, simmered pork belly sliced and served with spicy radish salad and salted cabbage leaves.",
        descZh: "选用优质猪五花肉配以韩方药材煮熟切片，配以秘制萝卜泡菜包食的白切肉",
        image: "assets/menu/bossam.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 1
    },

    // --------------------------------------------------------
    // DOSILAK (LUNCH BOX)
    // --------------------------------------------------------
    {
        id: "dosilak-l01",
        category: "dosilak",
        nameKo: "L01. 제육볶음도시락",
        nameEn: "Jeyuk Bokkeum Dosilak",
        nameZh: "辣炒猪肉便当",
        price: "RM 25.00",
        descKo: "매콤한 제육볶음(돼지 삼겹살)과 갓 지은 밥, 정갈한 밑반찬이 한데 담긴 든든한 점심 도시락",
        descEn: "Stir-fried sliced pork belly in a spicy chili marinade, served with steamed rice and side dishes.",
        descZh: "辣炒五花肉与白米饭及精选韩式小菜搭配的韩式工作便当",
        image: "assets/menu/jeyuk_bokkeum_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-65",
        category: "dosilak",
        nameKo: "L02. 불고기도시락",
        nameEn: "Bulgogi Dosilak",
        nameZh: "烤牛肉便当",
        price: "RM 25.00",
        descKo: "불고기, 밥, 반찬이 어우러진 알찬 소불고기 도시락",
        descEn: "Slices of prime beef simmered in its own juices and a special soya sauce broth served in a lunchbox.",
        descZh: "包含烤牛肉、米饭及各式配菜的韩式烤牛肉便当",
        image: "assets/menu/bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-66",
        category: "dosilak",
        nameKo: "L03. 돼지불고기도시락",
        nameEn: "DejiBulgogi Dosilak",
        nameZh: "辣炒猪肉便当",
        price: "RM 25.00",
        descKo: "매콤한 돼지불고기와 밥, 반찬이 어우러진 도시락",
        descEn: "Pork and assortment of vegetables stir-fried with Korean chili paste served in a lunchbox.",
        descZh: "包含辣炒猪肉、米饭及各式配菜 of 韩式辣炒猪肉便当",
        image: "assets/menu/dwaeji_bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-67",
        category: "dosilak",
        nameKo: "L04. 오징어볶음도시락",
        nameEn: "Ojingeo Bokeum Dosilak",
        nameZh: "辣炒鱿鱼便当",
        price: "RM 25.00",
        descKo: "매콤한 오징어볶음과 밥, 반찬이 함께 들어간 도시락",
        descEn: "Fried squid in a sauce of Korean chili paste served in a lunchbox.",
        descZh: "包含辣炒鱿鱼、米饭及各式配菜的韩式辣炒鱿鱼便当",
        image: "assets/menu/ojingeo_bokkeum_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-68",
        category: "dosilak",
        nameKo: "L05. 보쌈도시락",
        nameEn: "Bossam Dosilak",
        nameZh: "白切肉便当",
        price: "RM 25.00",
        descKo: "부드러운 수육 보쌈과 무말랭이, 밥, 반찬이 어우러진 도시락",
        descEn: "Special recipe steamed tender pork belly served in a lunchbox with side dishes.",
        descZh: "包含特制秘方清蒸软嫩白切肉、米饭及各式配菜的韩式白切肉便当",
        image: "assets/menu/bossam_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-l06",
        category: "dosilak",
        nameKo: "L06. 닭갈비도시락",
        nameEn: "Dakgalbi Dosilak",
        nameZh: "辣酱烤鸡肉便当",
        price: "RM 25.00",
        descKo: "춘천식 매콤달콤한 닭갈비 볶음과 따뜻한 밥, 다오래 정통 반찬들이 함께 어우러진 점심 도시락",
        descEn: "Spicy stir-fried chicken chunks in gochujang sauce, served with rice and traditional sides.",
        descZh: "春川风味辣炒鸡肉与白米饭及精选小菜搭配의 营养便当",
        image: "assets/menu/dakgalbi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-69",
        category: "dosilak",
        nameKo: "L07. 김치볶음도시락",
        nameEn: "Kimchi Bokkeum Dosilak",
        nameZh: "泡菜炒肉便当",
        price: "RM 25.00",
        descKo: "매콤하게 볶아낸 삼겹살 김치볶음과 밥, 반찬이 어우러진 도시락",
        descEn: "Belly pork fried with Kimchi served in a lunchbox with side dishes.",
        descZh: "包含泡菜炒五花肉、米饭及各式配菜의 韩式泡菜炒肉便当",
        image: "assets/menu/kimchi_bokkeum_dosilak.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-l08",
        category: "dosilak",
        nameKo: "L08. 비빔밥도시락",
        nameEn: "Bibimbap Dosilak",
        nameZh: "拌饭便当",
        price: "RM 25.00",
        descKo: "오색 나물과 볶은 소고기, 고추장 양념을 따로 담아 이동 중에도 신선하게 비벼 먹을 수 있는 비빔밥 도시락",
        descEn: "Korean mixed rice with seasoned vegetables, beef, and gochujang sauce, packed in a lunchbox.",
        descZh: "五色蔬菜和牛肉及特制辣酱搭配的韩式拌饭便当",
        image: "assets/menu/bibimbap_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },

    // --------------------------------------------------------
    // BEVERAGES
    // --------------------------------------------------------
    {
        id: "beverage-70",
        category: "beverage",
        nameKo: "V01. Coke",
        nameEn: "Coke",
        nameZh: "可口可乐",
        price: "RM 5.00",
        descKo: "코카콜라 탄산음료 (캔)",
        descEn: "CocaCola Soda Drink (Can)",
        descZh: "罐装可口可乐碳酸饮料",
        image: "assets/menu/coke.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-71",
        category: "beverage",
        nameKo: "V02. Sprite",
        nameEn: "Sprite",
        nameZh: "雪碧",
        price: "RM 5.00",
        descKo: "스프라이트 탄산음료 (캔)",
        descEn: "Sprite Soda Drink (Can)",
        descZh: "罐装雪碧碳酸饮料",
        image: "assets/menu/sprite.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-72",
        category: "beverage",
        nameKo: "V03. 100 Plus",
        nameEn: "100 Plus",
        nameZh: "100 Plus 运动饮料",
        price: "RM 5.00",
        descKo: "백플러스 이온음료 (캔)",
        descEn: "100 Plus Isotonic Drink (Can)",
        descZh: "罐装100 Plus等渗离子饮料",
        image: "assets/menu/100_plus.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-73",
        category: "beverage",
        nameKo: "V04. Galamanddeunbae",
        nameEn: "Galamanddeunbae",
        nameZh: "韩国海太梨汁",
        price: "RM 7.00",
        descKo: "국산 해태 갈아만든 배 시원한 음료 (캔)",
        descEn: "Korean Crushed Pear Juice (Can)",
        descZh: "罐装韩国海太碎梨汁",
        image: "assets/menu/galamanddeunbae.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-74",
        category: "beverage",
        nameKo: "V05. 소주",
        nameEn: "Soju",
        nameZh: "韩国烧酒",
        price: "RM 35.00",
        descKo: "한국 전통 소주 주류",
        descEn: "Traditional Korean Liquor (Soju)",
        descZh: "韩国传统烧酒",
        image: "assets/menu/soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-v06",
        category: "beverage",
        nameKo: "V06. 자몽 소주",
        nameEn: "Grapefruit Soju",
        nameZh: "西柚味烧酒",
        price: "RM 35.00",
        descKo: "상큼하고 달콤한 자몽 천연 즙을 블렌딩하여 여성들에게도 인기가 높은 과일 소주",
        descEn: "Sweet and tangy grapefruit-flavored Korean Soju.",
        descZh: "融入甜美西柚果汁的果味烧酒，入口清甜，备受欢迎",
        image: "assets/menu/grapefruit_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-v07",
        category: "beverage",
        nameKo: "V07. 청포도 소주",
        nameEn: "Green Grape Soju",
        nameZh: "青葡萄味烧酒",
        price: "RM 35.00",
        descKo: "싱그럽고 청량한 청포도 즙을 넣어 가볍고 달콤하게 즐길 수 있는 인기 과일 소주",
        descEn: "Refreshing and sweet green grape-flavored Korean Soju.",
        descZh: "融入爽口青葡萄果汁的果味烧酒，清新香甜",
        image: "assets/menu/greengrape_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-75",
        category: "beverage",
        nameKo: "V08. 레몬소주",
        nameEn: "Lemon Soju",
        nameZh: "柠檬烧酒",
        price: "RM 38.00",
        descKo: "상큼한 레몬을 블렌딩한 상쾌한 과일 소주",
        descEn: "Korean Liquor with Lemon",
        descZh: "柠檬风味烧酒",
        image: "assets/menu/lemon_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-76",
        category: "beverage",
        nameKo: "V09. 오이소주",
        nameEn: "Cucumber Soju",
        nameZh: "黄瓜烧酒",
        price: "RM 38.00",
        descKo: "시원하고 깔끔한 맛을 자랑하는 수제 오이 소주",
        descEn: "Korean Liquor infused with fresh Cucumber slices",
        descZh: "黄瓜风味烧酒",
        image: "assets/menu/cucumber_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-77",
        category: "beverage",
        nameKo: "V10. 타이거캔맥주",
        nameEn: "Tiger Beer (Can)",
        nameZh: "罐装虎牌啤酒",
        price: "RM 13.00",
        descKo: "청량감이 넘치는 수입 타이거 캔맥주",
        descEn: "Tiger Beer (Can)",
        descZh: "罐装虎牌啤酒",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-78",
        category: "beverage",
        nameKo: "V11. 타이거병맥주",
        nameEn: "Tiger Beer (Bottle)",
        nameZh: "瓶装虎牌啤酒",
        price: "RM 30.00",
        descKo: "시원하고 풍미가 살아있는 오리지널 타이거 병맥주",
        descEn: "Tiger Beer (Bottle)",
        descZh: "瓶装虎牌啤酒",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-79",
        category: "beverage",
        nameKo: "V12. 한국병맥주",
        nameEn: "Korean Beer",
        nameZh: "瓶装韩国啤酒 (Cass/Terra)",
        price: "RM 35.00",
        descKo: "한국 전통 라거 병맥주 (카스 또는 테라)",
        descEn: "Korean Beer (Bottle, e.g. Cass or Terra)",
        descZh: "瓶装韩国啤酒（Cass/Terra）",
        image: "assets/menu/korean_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-80",
        category: "beverage",
        nameKo: "V13. 오십세주",
        nameEn: "OShipSaeJu",
        nameZh: "五十岁酒",
        price: "RM 90.00",
        descKo: "소주와 백세주를 황금 비율로 섞어 차갑게 즐기는 한국 특제 믹스 약주",
        descEn: "Combination of Soju & BaekSaeJu in an ice chilled bottle.",
        descZh: "冰镇瓶装五十岁酒（烧酒与百岁酒的黄金比例调和酒）",
        image: "assets/menu/oshipsaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-81",
        category: "beverage",
        nameKo: "V14. 백세주",
        nameEn: "BaekSaeJu",
        nameZh: "百岁酒",
        price: "RM 60.00",
        descKo: "12가지 한약재를 넣어 빚은 깊은 맛의 한국 전통 한방 약주",
        descEn: "Korean Herbal Liquor brewed with 12 organic herbs.",
        descZh: "百岁酒（融合十二种草本药材酿制的传统韩国养生酒）",
        image: "assets/menu/baeksaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-82",
        category: "beverage",
        nameKo: "V15. 설중매",
        nameEn: "SeolJungMae",
        nameZh: "雪中梅梅子酒",
        price: "RM 65.00",
        descKo: "신선한 매실을 통째로 침출시켜 달콤하고 상큼한 프리미엄 매실주",
        descEn: "Korean Plum Wine featuring real green plums in the bottle.",
        descZh: "雪中梅梅子酒（采用优质青梅酿制的韩国高级梅子酒）",
        image: "assets/menu/seoljungmae.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-83",
        category: "beverage",
        nameKo: "V16. 복분자",
        nameEn: "BokBunJa",
        nameZh: "覆盆子酒",
        price: "RM 65.00",
        descKo: "달콤하고 떫은맛의 균형이 조화로운 건강 식물성 복분자주",
        descEn: "Korean Raspberry Wine known for its sweet, rich berry flavor and health benefits.",
        descZh: "覆盆子酒（采用优质覆盆子酿制的甘甜韩国覆盆子酒）",
        image: "assets/menu/bokbunja.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-v17",
        category: "beverage",
        nameKo: "V17. 막걸리",
        nameEn: "Makgeolli",
        nameZh: "韩国米酒 (马格利)",
        price: "RM 35.00",
        descKo: "쌀과 곡물을 발효시켜 만든 한국 전통 탁주로 걸쭉하고 유산균이 가득해 고소하고 톡 쏘는 맛의 막걸리",
        descEn: "Traditional Korean unfiltered rice wine with a sweet, milky, and slightly fizzy flavor.",
        descZh: "大米和谷物发酵酿制的传统韩式浊米酒，微甜爽口，乳酸菌丰富",
        image: "assets/menu/makgeolli.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    }
];
