// DAORAE KOREAN BBQ - BUKIT INDAH OUTLET
// Trilingual Menu Database File (Korean, English, Chinese)
// Updated prices matching official Bukit Indah menu.pdf

const MENU_ITEMS = [
    {
        id: "set-1",
        category: "set",
        nameKo: "SET1",
        nameEn: "3~4 pax",
        nameZh: "3~4 pax",
        price: "RM 248.00",
        descKo: "?쇱? ?ㅽ럹?? ?쇨껸?? 紐⑹궡, ?쇱?媛덈퉬, 怨좎텛???쇨껸?? 源移섏쟾怨? 遺異붿쟾",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Pork Ribs, Chili Sauce Pork Belly, Kimchi Hot Pot, Chive Pancake",
        descZh: "?よ굢?백됥곦틪?김굢?곫쥌?김굢?곫럲謠ⓦ곮쐽?긴틪?김굢?곫끝?쒐겓?끹곮뵮?쒐뀕耀?,
        image: "assets/menu/set1.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-2",
        category: "set",
        nameKo: "SET2",
        nameEn: "3~4 pax",
        nameZh: "3~4 pax",
        price: "RM 248.00",
        descKo: "?쇱? ?ㅽ럹?? ?쇨껸?? 紐⑹궡, ?묐뀗??컝鍮? ?묐뀗彛덇씀誘? 源移섏쟾怨? 遺異붿쟾",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Marinated Chicken, Marinated Spicy Webfoot Octopus, Kimchi Hot Pot, Chive Pancake",
        descZh: "?よ굢?백됥곦틪?김굢?곫쥌?김굢?곮컘?녜륫?됥곮컘?녑컦?ョ닼浴쇈곫끝?쒐겓?끹곮뵮?쒐뀕耀?,
        image: "assets/menu/set2.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 1
    },
    {
        id: "set-3",
        category: "set",
        nameKo: "SET3",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "?쇱? ?ㅽ럹?? ?쇨껸?? 紐⑹궡, 源移섏컡媛? 遺異붿쟾",
        descEn: "Pork Special, Pork Belly, Pork Shoulder, Kimchi Soup, Chive Pancake",
        descZh: "?よ굢?백됥곦틪?김굢?곫쥌?김굢?곫끝?쒏광?곮뵮?쒐뀕耀?,
        image: "assets/menu/set3.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-4",
        category: "set",
        nameKo: "SET4",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "??젙?? ?쇱?媛덈퉬, ?쇱? 二쇰Ъ?? 源移섏컡媛? 遺異붿쟾",
        descEn: "Pork Jowls, Pork Ribs, Marinated Pork Special, Kimchi Soup, Chive Pancake",
        descZh: "?ら씊窯딂굢?곭뙦?믧え?곮컘?녕돶?됬뙦?됥곫끝?쒏광?곮뵮?쒐뀕耀?,
        image: "assets/menu/set4.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-5",
        category: "set",
        nameKo: "SET5",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 138.00",
        descKo: "?쇱? ?ㅽ럹?? ?쇱?媛덈퉬, ??컝鍮? 源移섏컡媛? 遺異붿쟾",
        descEn: "Pork Special, Pork Ribs, Marinated Chicken, Kimchi Soup, Chive Pancake",
        descZh: "?よ굢?백됥곭뙦?믧え?곮컘?녜륫?됥곫끝?쒏광?곮뵮?쒐뀕耀?,
        image: "assets/menu/set5.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 0
    },
    {
        id: "set-6",
        category: "set",
        nameKo: "SET6",
        nameEn: "2~3 pax",
        nameZh: "2~3 pax",
        price: "RM 148.00",
        descKo: "?쇱?媛덈퉬, 留ㅼ슫 ??컝鍮? ?묐뀗彛덇씀誘? 源移섏컡媛? 遺異붿쟾",
        descEn: "Pork Ribs, Spicy Chicken, Spicy Baby Octopus, Kimchi Soup, Chive Pancake",
        descZh: "?ゆ럲謠ⓦ곮쐽?녜륫?됥곮쐽?녑컦?ョ닼浴쇈곫끝?쒏광?곮뵮?쒐뀕耀?,
        image: "assets/menu/set6.jpg",
        badge: "Best Combo",
        serving: "Shareable",
        spicy: 2
    },
    {
        id: "beef-7",
        category: "beef",
        nameKo: "B01. 媛덈퉬蹂몄궡",
        nameEn: "Galbi Bonsal",
        nameZh: "GALBI BONSAL",
        price: "RM 130.00",
        descKo: "?묐뀗?섏? ?딆? ?좎꽑??媛덈퉬蹂몄궡 ??텋援ъ씠 (媛덈퉬堉덈? ?쒓굅???뚭컝鍮꾩궡)",
        descEn: "Fresh boneless short rib without marinade, charcoal grilled",
        descZh: "?좄컘?녔뼭縟쒎렮謠①돍弱뤸럲竊뚨궘?ョ깶??,
        image: "assets/menu/galbi_bonsal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-8",
        category: "beef",
        nameKo: "B02. ?앷컝鍮?,
        nameEn: "Saeng Galbi",
        nameZh: "SAENG GALBI",
        price: "RM 130.00",
        descKo: "?묐뀗?섏? ?딄퀬 移쇱쭛???댁뼱 援ъ슫 ?꾪넻 ???뚭컝鍮꾧뎄??,
        descEn: "Beef short ribs butterflied or accordion cut, without marinade and char-grilled.",
        descZh: "?닺씢?뉑닑繇롧맭?뉒쉪?좄컘?녑컦?쎿럲竊뚨궘?ョ깶??,
        image: "assets/menu/saeng_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-9",
        category: "beef",
        nameKo: "B03. ?뺢컝鍮?,
        nameEn: "Wang Galbi",
        nameZh: "WANG GALBI",
        price: "RM 130.00",
        descKo: "?ㅼ삤???쒕갑 ?뱀젣 媛꾩옣 ?묐뀗?μ뿉 ?ъ썙 留쏆쓣 ???먯쭏 ?뚯솗媛덈퉬",
        descEn: "Beef short rib specially hand filleted marinated with special Daorae sauce",
        descZh: "瀯뤷ㄷ?얏씎?밧댍?길콅?뚦댍?꾤돶?됬변?뗥램?쎾컦??,
        image: "assets/menu/wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-10",
        category: "beef",
        nameKo: "B04. ?곗꽕援ъ씠",
        nameEn: "Wooseul Gui",
        nameZh: "WOOSEUL GUI",
        price: "RM 90.00",
        descKo: "已꾧퉫?섍퀬 遺?쒕윭??留쏆씠 ?쇳뭹???뉕쾶 ??理쒓퀬湲??곗꽕援ъ씠",
        descEn: "Thinly sliced Ox-tongue grilled over natural charcoal",
        descZh: "?꾢늾?쏂닃",
        image: "assets/menu/woo_seul_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-11",
        category: "beef",
        nameKo: "B05. ?뚭퀬湲곕え??,
        nameEn: "Beef Modum",
        nameZh: "BEEF MODUM",
        price: "RM 320.00",
        descKo: "?뚭퀬湲?4媛吏 遺??紐⑤몺 援ъ꽦 (?곗꽕, 媛덈퉬蹂몄궡, 李⑤룎諛뺤씠, 媛덈퉬??",
        descEn: "Four kinds of assorted beef BBQ sampler (Ox tongue, boneless short rib, brisket, short rib)",
        descZh: "?쏁쭕?백됬돍?됬퍍?덌펷?쏂닃?곩렮謠①돍弱뤸럲?곭돍?멱굢?곭돍?뗦씉竊?,
        image: "assets/menu/beep_modum.jpg",
        badge: "",
        serving: "2-3 Pax",
        spicy: 0
    },
    {
        id: "beef-12",
        category: "beef",
        nameKo: "B06. LA 媛덈퉬",
        nameEn: "LA Galbi",
        nameZh: "LA GALBI",
        price: "RM 125.00",
        descKo: "堉덉㎏ 吏곴컖 諛⑺뼢?쇰줈 ?섎씪 ??뚯? 留덈뒛???ｌ? ?뱀젣 媛꾩옣 ?묐뀗???ъ슫 ?뚭컝鍮꾧뎄??,
        descEn: "Short ribs cut through the bone and marinated in soy sauce, onion, and garlic",
        descZh: "LA?믧え??컛?닸씉?믧え?뉑닇訝롩え鸚닷몚?닺쭜?밧릲竊뚦숱?먫퓹謠ⓨ를?됬쉪T謠①돍?믭펽訝삭쫨??걳?㎫깶?뽫굷?믧え??,
        image: "assets/menu/la_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-13",
        category: "beef",
        nameKo: "B07. 媛덈퉬?댁＜臾쇰윮",
        nameEn: "Galbisal",
        nameZh: "GALBISAL",
        price: "RM 125.00",
        descKo: "堉덈? 諛붾Ⅸ 媛덈퉬?댁쓣 利됱꽍?먯꽌 ?뱀젣 留덈뒛 媛꾩옣 ?뚯뒪濡?二쇰Ъ??議곕━??援ъ씠",
        descEn: "Boneless short ribs marinated in garlic-based special sauce",
        descZh: "瀯뤷ㄷ?얏씎?밧댍?길콅?뚦댍?꾣뿞謠①돍?뗦씉",
        image: "assets/menu/galbi_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "beef-14",
        category: "beef",
        nameKo: "B08. ?곗궪寃?,
        nameEn: "Woosamgyeop",
        nameZh: "WOOSAMGYEOP",
        price: "RM 80.00",
        descKo: "遺?쒕읇怨?吏諛⑹씠 ?띾????묐뀗?섏? ?딆? 李⑤룎 ?곗궪寃뱀궡 援ъ씠",
        descEn: "Thinly sliced, richly marbled beef without marinade",
        descZh: "?좄컘?녘뻹?뉔쎀?김궏??,
        image: "assets/menu/woo_samgyeop.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-15",
        category: "pork",
        nameKo: "P01. ?쇱??ㅽ럹??,
        nameEn: "Pork Special",
        nameZh: "PORK SPECIAL",
        price: "RM 45.00",
        descKo: "?쇱? 癒몃━?먯꽌 ?살? 遺?쒕읇怨?已꾧퉫???앷컧???뱀닔 遺??(?쒕???",
        descEn: "Specially selected cuts of pork that is soft and tender",
        descZh: "訝ι됭쉴椰⑴뙦??쥓??,
        image: "assets/menu/dwaeji_special.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-16",
        category: "pork",
        nameKo: "P02. ??젙??,
        nameEn: "Hangjungsal",
        nameZh: "HANGJUNGSAL",
        price: "RM 45.00",
        descKo: "泥쒓껸?댁씠??遺덈━???쇱? 紐⑸뜙誘몄쓽 已꾧퉫?섍퀬 留덈툝留곸씠 ?곗닔????젙??援ъ씠",
        descEn: "Pork Jowls grilled over natural charcoal",
        descZh: "??깶?뉒뎴?ら쥏?됵펷容꾦뇫??륵竊?,
        image: "assets/menu/hang_jung_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-17",
        category: "pork",
        nameKo: "P03. 紐⑹궡",
        nameEn: "Moksal",
        nameZh: "MOKSAL",
        price: "RM 38.00",
        descKo: "湲곕쫫湲곌? ?곴퀬 ?대갚?섏뿬 ??텋援ъ씠??媛???곹빀???좎꽑??紐⑹궡 紐⑸벑??,
        descEn: "Pork Shoulder cut into thick slices and grilled over charcoal",
        descZh: "??깶?곈쿇?ゆ쥌?김굢竊덅궔?쏂굢竊?,
        image: "assets/menu/mok_sal.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-18",
        category: "pork",
        nameKo: "P04. ?쇨껸??,
        nameEn: "Samgyeopsal",
        nameZh: "SAMGYEOPSAL",
        price: "RM 38.00",
        descKo: "?댁퐫湲곗? 吏諛⑹씠 ??寃뱀쑝濡??섏뼱 ?덉뼱 遺?쒕읇怨?怨좎냼???쇨껸??援ъ씠",
        descEn: "Pork Belly grilled and dipped in salt or ssamjang (red soybean paste dip)",
        descZh: "雅붻뒻?됪삸?よ굾?⑶깿鵝띸쉪?됵펽?좂삧???뚩꼥?や벡?울펽?餓θ굢兀②쉴椰⒴룾?ｃ귚??ф삸?잒굢 ?닸렏訝딁겓??,
        image: "assets/menu/samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-19",
        category: "pork",
        nameKo: "P05. 怨좎텛???쇨껸??,
        nameEn: "Gochujang Samgyeopsal",
        nameZh: "GOCHUJANG SAMGYEOPSAL",
        price: "RM 42.00",
        descKo: "?쇨껸?댁뿉 留ㅼ숴?ъ숴??怨좎텛???묐뀗??踰꾨Т????텋 ?μ쓣 ?낇엺 ?묐뀗援ъ씠",
        descEn: "Pork belly marinated in spicy Korean chili paste",
        descZh: "弱녵틪?김굢?②쐽濾믧뀻?싨닇?꾥컘?녜뀻?끾땶?롳펽?ㅷ??껅닑?믥??껃뜵??귞뵪渦ｆ쨸?김컘?녕쉪雅붻뒻?됭궏?뚥툖?삼펽?욃만腰쇿ォ??,
        image: "assets/menu/gochujang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-20",
        category: "pork",
        nameKo: "P06. ?묐뀗 ?쇱?媛덈퉬",
        nameEn: "Yangnyeom Dwaeji Galbi",
        nameZh: "YANGNYEOM DWAEJI GALBI",
        price: "RM 42.00",
        descKo: "?쇱?媛덈퉬?瑜??뱀젣 媛꾩옣 ?묐뀗?μ뿉 ?ъ썙 ?≪쬂??媛?앺븯怨?媛먯튌留??섎뒗 援ъ씠",
        descEn: "Pork marinated in soy sauce, garlic, and sweet onion marinade",
        descZh: "弱녺뙦?믦굢?②컘?녔콅?뚧툖餓ε릮?얍댆???ヤ툓?ㅷ넖?녑룾??,
        image: "assets/menu/yangnyeom_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-21",
        category: "pork",
        nameKo: "P07. ?쒕갑 ?쇱??뺢컝鍮?,
        nameEn: "Hanbang Dwaeji Wang Galbi",
        nameZh: "HANBANG DWAEJI WANG GALBI",
        price: "RM 48.00",
        descKo: "移쇱쭛?????쇱쭅???쇱?媛덈퉬瑜??꾩꽑???몄궪, ?쎌큹 異붿텧臾쇨낵 ?뱀젣 媛꾩옣????嫄닿컯 援ъ씠",
        descEn: "Pork ribs marinated in Korean ginseng, herb extracts, and soy sauce",
        descZh: "瀯뤹쭣?뜸볶?귙곲윪?배뜆?ф룓?뽫돥?듿ㄷ?얏씎?밧댍?길콅?뚦댍?꾤돶?됧ㄷ?ゆ럲",
        image: "assets/menu/hanbang_dwaeji_wang_galbi.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-22",
        category: "pork",
        nameKo: "P08. ?쇱? 二쇰Ъ??,
        nameEn: "Dwaeji Jumulluk",
        nameZh: "DWAEJI JUMULLUK",
        price: "RM 47.00",
        descKo: "?꾩꽑???쇱?怨좉린 ?댁퐫湲곕? 利됱꽍?먯꽌 留덈뒛怨??ъ숴???ㅼ삤??媛꾩옣 ?뚯뒪??議곕━??二쇰Ъ??,
        descEn: "Selected cuts of soft pork marinated in special Daorae sauce",
        descZh: "瀯뤷ㄷ?얏씎?밧댍?길콅?뚦댍?꾥쉴椰⑴뙦?뗦씉??,
        image: "assets/menu/dwaeji_jumulluk.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "pork-23",
        category: "pork",
        nameKo: "P09. 留ㅼ슫 ?쇱?媛덈퉬",
        nameEn: "Maeun Dwaeji Galbi",
        nameZh: "MAEUN DWAEJI GALBI",
        price: "RM 42.00",
        descKo: "?섏젣 ?먯쭏???꾩꽑???쇱?怨좉린瑜?留ㅼ숴??援?궛 泥?뼇怨좎텛 怨좎때媛猷??묐뀗?μ뿉 ?ъ슫 援ъ씠",
        descEn: "Pork marinated in spicy Korean chili sauce and soy sauce",
        descZh: "瀯뤻윪凉뤺쐽?김뀒?띄쉪瀛?뎸藥η돶?됭쐽?ゆ럲",
        image: "assets/menu/maeun_dwaeji_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "pork-24",
        category: "pork",
        nameKo: "P10. ?쒕갑 ?쇨껸??,
        nameEn: "Hanbang Samgyeopsal",
        nameZh: "HANBANG SAMGYEOPSAL",
        price: "RM 45.00",
        descKo: "?좎꽑???쇨껸?댁뿉 ?뱀젣 ?몄궪 諛?紐몄뿉 醫뗭? ?쒕갑 ?쎌큹 異붿텧臾쇱쓣 ?낇? ?숈꽦?쒗궓 ?쇨껸??援ъ씠",
        descEn: "Slices of pork belly marinated in special Korean ginseng and herbs extract",
        descZh: "瀯뤹쭣?뜸볶?귛룋?⒵뼶?됪쑍 異붿텧臾??뚦댍?꾢늾?뉏틪?김굢",
        image: "assets/menu/hanbang_samgyeopsal.jpg",
        badge: "Signature",
        serving: "200g",
        spicy: 0
    },
    {
        id: "other-bbq-25",
        category: "other-bbq",
        nameKo: "M01. ?묐뀗 ??컝鍮?,
        nameEn: "Yangnyeom Dakgalbi",
        nameZh: "YANGNYEOM DAKGALBI",
        price: "RM 38.00",
        descKo: "遺?쒕윭????떎由ъ궡??怨좎텛???묐뀗?μ뿉 ?ъ썱?ㅺ? ??텋??援ъ썙 癒밸뒗 媛뺤썝??異섏쿇??蹂꾨? ?붾━",
        descEn: "Chicken marinated in Daorae sauce and cooked on a charcoal grill",
        descZh: "勇↑굢?②쐽濾믧뀻瘟껃댍?꾥컘?녜뀻?뚥?鴉싧꽴竊뚦뀯?녑릮?얍쑉??겓訝딁깶?잌뜵??,
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-26",
        category: "other-bbq",
        nameKo: "M02. ??컝鍮?,
        nameEn: "Dak Galbi",
        nameZh: "DAK GALBI",
        price: "RM 38.00",
        descKo: "吏諛⑹씠 ?곴퀬 ?대갚??????댁궡 諛???젙??遺?꾨? 泥?뼇 怨좎때媛猷??뱀젣 留ㅼ슫 ?묐뀗???ъ슫 ?붾━",
        descEn: "Lean skinless chicken fillets marinated in our hot chili sauce",
        descZh: "渦ｅ뫑瘟껈뀻?뚦댍?꾢렮??렮謠ⓩ뿞?귡륫?멱굢",
        image: "assets/menu/dak_galbi.jpg",
        badge: "",
        serving: "200g",
        spicy: 1
    },
    {
        id: "other-bbq-27",
        category: "other-bbq",
        nameKo: "M03. ?묐뀗 ?묎퀬湲?,
        nameEn: "Yangnyeom Yanggogi",
        nameZh: "YANGNYEOM YANGGOGI",
        price: "RM 52.00",
        descKo: "?꾩꽑??怨좉툒 ?묎퀬湲??댁퐫湲곕? ?섏젣 ?먯쭏?섏뿬 ?ㅼ삤???뱀젣 媛덈퉬 ?뚯뒪??踰꾨Т??援ъ슫 ?묎퀬湲?,
        descEn: "Chosen cuts of lamb specially hand filleted, marinated in special Daorae sauce",
        descZh: "瀯뤷ㄷ?얏씎?밧댍?길콅?뚦댍?꾤돶?됬변?뗥램獰딂굢",
        image: "assets/menu/yangnyeom_yanggogi.jpg",
        badge: "",
        serving: "200g",
        spicy: 0
    },
    {
        id: "other-bbq-28",
        category: "other-bbq",
        nameKo: "M04. ?묐뀗 ?ㅼ쭠?닿뎄??,
        nameEn: "Yangnyeom Ojingeo Gui",
        nameZh: "YANGNYEOM OJINGEO GUI",
        price: "RM 57.00",
        descKo: "?좎꽑?섍퀬 ?듯넻???ㅼ쭠?댁뿉 移쇱쭛???댁뼱 ?ㅼ삤???뱀젣 怨좎텛??留ㅼ슫 ?뚯뒪瑜?怨곷뱾???앹뇿??援ъ슫 ?붾━",
        descEn: "Fresh squid carved and prepared in our hot chili sauce",
        descZh: "瀯뤹돶?띈쐽?김컘?녕깶?띄쉪?곈쿇浴욥굴",
        image: "assets/menu/yangnyeom_ojingeo_gui.png",
        badge: "",
        serving: "200g",
        spicy: 2
    },
    {
        id: "other-bbq-29",
        category: "other-bbq",
        nameKo: "M05. ?묐뀗 彛덇씀誘멸뎄??,
        nameEn: "Yangnyeom Jukkumi Gui",
        nameZh: "YANGNYEOM JUKKUMI GUI",
        price: "RM 57.00",
        descKo: "?좎꽑??彛덇씀誘몃? ?먯쭏??遺?留?媛?앺븳 ?ㅼ삤??怨좎텛???뱀젣 留ㅼ슫 ?묐뀗 ?뚯뒪??留쏆엳寃?援ъ슫 ?붾━",
        descEn: "Fresh baby octopus carved and prepared in our hot chili sauce",
        descZh: "瀯뤹돶?띈쐽?김컘?녕깶?띄쉪?곈쿇弱뤷뀵?ら굴",
        image: "assets/menu/jjuggumi_gui.jpg",
        badge: "",
        serving: "200g",
        spicy: 3
    },
    {
        id: "stew-30",
        category: "stew",
        nameKo: "S01. 源移섏컡媛?,
        nameEn: "Kimchi Jjigae",
        nameZh: "KIMCHI JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "???듭? ?좉?移섏뿉 遺?쒕윭???쇱?怨좉린, 怨좎냼???먮?, ??뚮? ?щ퓤 ?ｌ뼱 ?쇳겙?섍퀬 源딆? 留쏆쓣 ???쒓뎅?몄쓽 ?뚯슱?몃뱶",
        descEn: "Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean soul food.",
        descZh: "弱녽끂力↑룣?얍뀯?끺릎竊뚦냽?졾뀯?よ굢?곮콊?먧빳?듿늾?먪쿁訝앯쉪?긺춬?먩뼑?뽫뀸?녑룾??,
        image: "assets/menu/kimchi_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-31",
        category: "stew",
        nameKo: "S02. ?쒖옣李뚭컻",
        nameEn: "Doenjang Jjigae",
        nameZh: "DOENJANG JJIGAE (SEAFOOD)",
        price: "RM 30.00",
        descKo: "硫몄튂 ?≪닔??援ъ닔???щ옒???쒖옣???怨??좎꽑??議곌컻瑜? ?먮?, ?좏샇諛뺤쓣 ?ｌ뼱 ?볦씤 諛λ룄??李뚭컻",
        descEn: "Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash.",
        descZh: "遙섉광訝?붂?εㄷ?깍펽?띶뒥?θ굢?곲굴兀앯굳?곮콊?먦곮??ヨ뒭嶺됬넭??뜵???,
        image: "assets/menu/doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-32",
        category: "stew",
        nameKo: "S03. ?쒕몢遺李뚭컻",
        nameEn: "Sundubu Jjigae",
        nameZh: "SUNDUBU JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "紐쎄?紐쎄????쒕몢遺? ?ㅼ쭊 ?쇱?怨좉린, ?좎꽑???쇱콈瑜??ｊ퀬 ?쇳겙??怨좎텛湲곕쫫 ?≪닔濡?留쏆쓣 ??李뚭컻 (?좊떖嫄 異붽? 媛??",
        descEn: "Soft bean curd stew boiled with minced pork and vegetables in a spicy red chili broth.",
        descZh: "?①쟼?끺릎?얍뀯椰⑵콊?먨뭽?よ굢?곮뵮?쒙펽?띶뒥?θ쐽遙섉광, 窈뜸툓?€돀?ζ뼭縟쒒륫??,
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-33",
        category: "stew",
        nameKo: "S04. ?대Ъ?쒕몢遺李뚭컻",
        nameEn: "Haemul Sundubu Jjigae",
        nameZh: "HAEMUL SUNDUBU JJIGAE (SEAFOOD)",
        price: "RM 28.00",
        descKo: "遺?쒕윭???쒕몢遺???좎꽑??寃? ?덉슦, 議곌컻瑜???紐⑤벉 ?대Ъ???щ퓤 ?ｌ뼱 諛붾떎???쒖썝?섍퀬 ?쇳겙??留쏆쓣 ?대┛ 李뚭컻",
        descEn: "Soft bean curd stew boiled with assorted seafood (shrimps, clams) in a spicy, flavorful broth.",
        descZh: "?①쟼?끺릎?얍뀯椰⑵콊?먨뭽?얇곮썶?딁춬役룬쿇竊뚦냽?졾뀯遙섉광?х뀸?뚧닇竊뚦릡壅룡씎?곩늽?썲룭",
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "stew-34",
        category: "stew",
        nameKo: "S05. 蹂댁뒪?쒖옣李뚭컻",
        nameEn: "Boss Doenjang Jjigae",
        nameZh: "BOSS DOENJANG JJIGAE (BEEF)",
        price: "RM 30.00",
        descKo: "吏꾪븯寃??볦씤 ?꾪넻 ?쒖떇 ?쒖옣 ?≪닔??遺?쒕윭??李⑤룎諛뺤씠 ?뚭퀬湲? ?먮?, ?쇱콈瑜??꾨굦?놁씠 ?ｌ? ?꾨━誘몄뾼 ?쒖옣李뚭컻",
        descEn: "Tofu and fresh vegetables in a rich traditional Korean bean broth topped with beef, served with rice.",
        descZh: "?ⓧ폖瀯잏쉪?⒴폀役볣긽鸚㏝뀻黎ㅴ릎?졾뀯?쏂굢?곮콊?먨뭽?곈쿇?ц룣?у댍?꾢ㄷ?길광",
        image: "assets/menu/boss_doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-35",
        category: "stew",
        nameKo: "S08. 媛덈퉬??,
        nameEn: "Galbitang",
        nameZh: "GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "?뤿Ъ??類 ?뚭컝鍮꾩? ?쇱쭅??臾대? 媛留덉넡?먯꽌 ??怨좎븘 留묎퀬 ?쒖썝???≪닔媛 ?쇳뭹?????蹂댁뼇??媛덈퉬??,
        descEn: "Beef ribs and white radish chunks simmered together until tender. The clear stock is rich and savory.",
        descZh: "?①돍?믧え?х쉪黎ㅿ펽?쎿럲謠ⓩ돋力▼렮烏?롣툗?앭뜙訝壅루넭??눛?됬긾竊뚥툖鵝녷광黎곲쬂??,
        image: "assets/menu/galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-36",
        category: "stew",
        nameKo: "S09. ?곌굅吏媛덈퉬??,
        nameEn: "Ugeoji Galbitang",
        nameZh: "UGEOJI GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "?뚭컝鍮꾨? ?볦뿬???≪닔??援ъ닔???쒓낏 ?쒖옣怨??앹씠?ъ쑀媛 ?띾????곌굅吏瑜????볦뿬?댁뼱 ?꾩옣??醫뗭? 嫄닿컯 ??,
        descEn: "Napa cabbage leaves slowly simmered in a beef rib stock and seasoned with traditional doenjang (soybean paste).",
        descZh: "?ⓩ럲謠③빣?띌뿴?х뀸?뜻닇遙섉광竊뚦냽?얍뀯力▼룕?꾢묾?썼룣?뚦ㄷ?긺넭???,
        image: "assets/menu/ugeoji_galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "stew-37",
        category: "stew",
        nameKo: "S10. ?↔컻??,
        nameEn: "Yukgaejang",
        nameZh: "YUKGAEJANG (BEEF)",
        price: "RM 38.00",
        descKo: "???묒?癒몃━瑜?怨좎븘 怨좎궗由? ??? ?좊?? ?깆쓽 ?섎Ъ???ｊ퀬 遺됱? 怨좎텛湲곕쫫?쇰줈 留듦퀬 ?쇳겙?섍쾶 ?묐뀗??蹂댁뼇??,
        descEn: "A spicy soup made of shredded beef brisket, radish, green onions, bean sprouts, and fiddleheads.",
        descZh: "?①돍?꾣럲謠ⓨ뭽?앭뜙嶺됮빣?띌뿴?х뀸竊뚦냽?졾뀯鸚㎬뫏?곲쓵?뗨뙉?곮븿?쒎뭽渦ｆ쨸暎됬춬瘟껃뫑?뚧닇??,
        image: "assets/menu/yukgaejang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 2
    },
    {
        id: "hotpot-38",
        category: "hotpot",
        nameKo: "S03. ?쒕몢遺李뚭컻",
        nameEn: "Sundubu Jjigae",
        nameZh: "SUNDUBU JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "紐쎄?紐쎄????쒕몢遺? ?ㅼ쭊 ?쇱?怨좉린, ?좎꽑???쇱콈瑜??ｊ퀬 ?쇳겙??怨좎텛湲곕쫫 ?≪닔濡?留쏆쓣 ??李뚭컻 (?좊떖嫄 異붽? 媛??",
        descEn: "Soft bean curd stew boiled with minced pork and vegetables in a spicy red chili broth.",
        descZh: "?①쟼?끺릎?얍뀯椰⑵콊?먨뭽?よ굢?곮뵮?쒙펽?띶뒥?θ쐽遙섉광, 窈뜸툓?€돀?ζ뼭縟쒒륫??,
        image: "assets/menu/sundubu_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "hotpot-39",
        category: "hotpot",
        nameKo: "S01. 源移섏컡媛?,
        nameEn: "Kimchi Jjigae",
        nameZh: "KIMCHI JJIGAE (PORK)",
        price: "RM 28.00",
        descKo: "???듭? ?좉?移섏뿉 遺?쒕윭???쇱?怨좉린, 怨좎냼???먮?, ??뚮? ?щ퓤 ?ｌ뼱 ?쇳겙?섍퀬 源딆? 留쏆쓣 ???쒓뎅?몄쓽 ?뚯슱?몃뱶",
        descEn: "Over-fermented kimchi boiled with pork, bean curd, and green onion. Often considered Korean soul food.",
        descZh: "弱녽끂力↑룣?얍뀯?끺릎竊뚦냽?졾뀯?よ굢?곮콊?먧빳?듿늾?먪쿁訝앹쓽?긺춬?먩뼑?뽫뀸?녑룾??,
        image: "assets/menu/kimchi_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "hotpot-40",
        category: "hotpot",
        nameKo: "S02. ?쒖옣李뚭컻",
        nameEn: "Doenjang Jjigae",
        nameZh: "DOENJANG JJIGAE (SEAFOOD)",
        price: "RM 30.00",
        descKo: "硫몄튂 ?≪닔??援ъ닔???щ옒???쒖옣???怨??좎꽑??議곌컻瑜? ?먮?, ?좏샇諛뺤쓣 ?ｌ뼱 ?볦씤 諛λ룄??李뚭컻",
        descEn: "Doenjang-seasoned stew made with anchovy broth, fish or clams, and summer squash.",
        descZh: "遙섉광訝?붂?εㄷ?깍펽?띶뒥?θ굢?곲굴兀앯굳?곮콊?먦곮??ヨ뒭嶺됬넭??뜵???,
        image: "assets/menu/doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-41",
        category: "hotpot",
        nameKo: "S05. 蹂댁뒪?쒖옣李뚭컻",
        nameEn: "Boss Doenjang Jjigae",
        nameZh: "BOSS DOENJANG JJIGAE (BEEF)",
        price: "RM 30.00",
        descKo: "吏꾪븯寃??볦씤 ?꾪넻 ?쒖떇 ?쒖옣 ?≪닔??遺?쒕윭??李⑤룎諛뺤씠 ?뚭퀬湲? ?먮?, ?쇱콈瑜??꾨굦?놁씠 ?ｌ? ?꾨━誘몄뾼 ?쒖옣李뚭컻",
        descEn: "Tofu and fresh vegetables in a rich traditional Korean bean broth topped with beef, served with rice.",
        descZh: "?ⓧ폖瀯잏쉪?⒴폀役볣긽鸚㏝뀻黎ㅴ릎?졾뀯?쏂굢?곮콊?먨뭽?곈쿇?ц룣?у댍?꾢ㄷ?길광",
        image: "assets/menu/boss_doenjang_jjigae.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-42",
        category: "hotpot",
        nameKo: "S08. 媛덈퉬??,
        nameEn: "Galbitang",
        nameZh: "GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "?뤿Ъ??類 ?뚭컝鍮꾩? ?쇱쭅??臾대? 媛留덉넡?먯꽌 ??怨좎븘 留묎퀬 ?쒖썝???≪닔媛 ?쇳뭹?????蹂댁뼇??媛덈퉬??,
        descEn: "Beef ribs and white radish chunks simmered together until tender. The clear stock is rich and savory.",
        descZh: "?①돍?믧え?х쉪黎ㅿ펽?쎿럲謠ⓩ돋力▼렮烏?롣툗?앭뜙訝壅루넭??눛?됬긾竊뚥툖鵝녷광黎곲쬂??,
        image: "assets/menu/galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-43",
        category: "hotpot",
        nameKo: "S09. ?곌굅吏媛덈퉬??,
        nameEn: "Ugeoji Galbitang",
        nameZh: "UGEOJI GALBITANG (BEEF)",
        price: "RM 40.00",
        descKo: "?뚭컝鍮꾨? ?볦뿬???≪닔??援ъ닔???쒓낏 ?쒖옣怨??앹씠?ъ쑀媛 ?띾????곌굅吏瑜????볦뿬?댁뼱 ?꾩옣??醫뗭? 嫄닿컯 ??,
        descEn: "Napa cabbage leaves slowly simmered in a beef rib stock and seasoned with traditional doenjang (soybean paste).",
        descZh: "?ⓩ럲謠③빣?띌뿴?х뀸?뜻닇遙섉광竊뚦냽?얍뀯力▼룕?꾢묾?썼룣?뚦ㄷ?긺넭???,
        image: "assets/menu/ugeoji_galbi_tang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "hotpot-44",
        category: "hotpot",
        nameKo: "S10. ?↔컻??,
        nameEn: "Yukgaejang",
        nameZh: "YUKGAEJANG (BEEF)",
        price: "RM 38.00",
        descKo: "???묒?癒몃━瑜?怨좎븘 怨좎궗由? ??? ?좊?? ?깆쓽 ?섎Ъ???ｊ퀬 遺됱? 怨좎텛湲곕쫫?쇰줈 留듦퀬 ?쇳겙?섍쾶 ?묐뀗??蹂댁뼇??,
        descEn: "A spicy soup made of shredded beef brisket, radish, green onions, bean sprouts, and fiddleheads.",
        descZh: "?①돍?꾣럲謠ⓨ뭽?앭뜙嶺됮빣?띌뿴?х뀸竊뚦냽?졾뀯鸚㎬뫏?곲쓵?뗨뙉?곮븿?쒎뭽渦ｆ쨸暎됬춬瘟껃뫑?뚧닇??,
        image: "assets/menu/yukgaejang.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 2
    },
    {
        id: "rice-45",
        category: "rice",
        nameKo: "R01. ?뚯넡鍮꾨퉼諛?,
        nameEn: "Dolsot Bibimbap",
        nameZh: "DOLSOT BIBIMBAP",
        price: "RM 30.00",
        descKo: "?④굅???뚯넡??諛κ낵 ?좎꽑???ㅼ깋 ?섎Ъ, 蹂띠? ?뚭퀬湲? 怨꾨? ?몃Ⅸ?먮? ?щ젮 怨좎텛?μ뿉 鍮꾨꼈 癒밸뒗 ?쒖떇 ???鍮꾨퉼諛?,
        descEn: "Bibimbap served in a sizzling hot stone pot. The crispy rice at the bottom, mixed with various toppings and gochujang.",
        descZh: "?ⓨ뒥??쓽?녜봾訝?늽?ユ붂?η교耀?곩릢燁띸킔?쒎뭽?믦굢訝앾펽?②쐽濾믧뀻?뽭뀻亦방릣?뚦뜵???,
        image: "assets/menu/dolsot_bibimbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-46",
        category: "rice",
        nameKo: "R03. ?뚮텋怨좉린蹂띠쓬諛?,
        nameEn: "Beef Bulgogi Bokkeumbap",
        nameZh: "BEEF BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "遺?쒕읇怨?吏?“由꾪븳 ?뚮텋怨좉린? ?쇱콈瑜?諛κ낵 ?④퍡 泥좏뙋?먯꽌 怨좎냼?섍쾶 蹂띠븘???뚮텋怨좉린 蹂띠쓬諛?,
        descEn: "Stir-fried rice with tender, savory beef bulgogi and fresh vegetables.",
        descZh: "腰숁탶?ㅷ돍?됦툗鸚㎫교耀?뭽?ц룣?③뱚?요툓?믣댍?꾤풆?녕깶?됬굮耀?,
        image: "assets/menu/beep_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-47",
        category: "rice",
        nameKo: "R04. ?쇱?遺덇퀬湲곕낭?뚮갈",
        nameEn: "Dwaeji Bulgogi Bokkeumbap",
        nameZh: "DWAEJI BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "留ㅼ숴?ъ숴??怨좎텛???쇱?遺덇퀬湲??뚯뒪濡?諛κ낵 ?쇱콈瑜?留쏆엳寃?遺?留쏅굹寃?蹂띠븘??蹂띠쓬諛?,
        descEn: "Stir-fried rice with sweet and spicy pork bulgogi and assorted vegetables.",
        descZh: "?⒴폀渦ｇ굮?よ굢訝롧교耀?룋縟쒐뼅訝壅루굮?띄쉪遙섉꽏佯?뙦?됬굮耀?,
        image: "assets/menu/dwaeji_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-48",
        category: "rice",
        nameKo: "R05. 源移섎낭?뚮갈",
        nameEn: "Kimchi Bokkeumbap",
        nameZh: "KIMCHI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "?좉?移섏? 踰좎씠而??먮뒗 怨좉린瑜?蹂띠? ??李멸린由꾩쓣 ?먮Ⅸ 蹂띠쓬諛??꾩뿉 諛붿궘??怨꾨??꾨씪?대? ?뱀? ?붾━",
        descEn: "Kimchi fried rice with meat, topped with a fried egg and seaweed flakes.",
        descZh: "力↑룣?뚨교耀?굮?띰펽亮띌뀓餓η뀕?뗧쉪力↑룣?믧?",
        image: "assets/menu/kimchi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "rice-49",
        category: "rice",
        nameKo: "R06. ?≪콈蹂띠쓬諛?,
        nameEn: "Japchae Bokkeumbap",
        nameZh: "JAPCHAE BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "?쒖떇 ?붿튂 ?붾━???밸㈃ ?≪콈? 諛μ쓣 ?④퍡 ??遺덉뿉 蹂띠븘??已꾧퉫?섍퀬 怨좎냼???≪콈 蹂띠쓬諛?,
        descEn: "Korean glass noodle (Japchae) and rice pan fried with assorted seasoned vegetables.",
        descZh: "?⒴폀?귟룣竊덄벚???暎됬쾳訝앾펹訝롥릢映삭컘?녘뵮?쒎뭽映녜??뚨굮?꾣쓡?쒐굮耀?,
        image: "assets/menu/japchae_bokkeumbap.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "rice-50",
        category: "rice",
        nameKo: "R07. 二쇰㉨諛?,
        nameEn: "Jumeokbap",
        nameZh: "JUMEOKBAP",
        price: "RM 20.00",
        descKo: "?곕쑜??諛μ뿉 怨좎냼??李멸린由? ?듦묠, 議곕? 源媛猷⑤? 議곕Ъ議곕Ъ 踰꾨Т???????ш린濡??숆??숆??섍쾶 萸됱튇 二쇰㉨諛?,
        descEn: "Hand-rolled rice balls seasoned with fragrant sesame oil, sesame seeds, and seaweed flakes.",
        descZh: "?뚦뀯役룩땾閻롥뭽?ц룣?뗥램?뤸닇?꾢쐠壤????,
        image: "assets/menu/jumeokbap.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "rice-51",
        category: "rice",
        nameKo: "R08. 怨듦린諛?,
        nameEn: "Bap",
        nameZh: "BAP",
        price: "RM 6.00",
        descKo: "留ㅼ옣?먯꽌 留ㅼ씪 ?좎꽑?섍쾶 吏? 怨좎뒳怨좎뒳?섍퀬 李곗쭊 ???諛?怨듦린諛?,
        descEn: "Freshly steamed white sticky rice bowl.",
        descZh: "?썹교耀?,
        image: "assets/menu/bap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-52",
        category: "noodle",
        nameKo: "N03. 臾쇰깋硫?,
        nameEn: "Mul Naengmyeon",
        nameZh: "MUL NAENGMYEON",
        price: "RM 28.00",
        descKo: "硫붾? 硫댁쓣 ?띠븘 ?숈튂誘?援?Ъ怨??뚭퀬湲??≪닔 ?욎? 援?Ъ??李④컩寃?留먯븘 癒밸뒗 ?뚯떇?대떎. 臾? 諛? ?깆쓣 ?밴퀬 寃⑥옄? ?앹큹濡??묐뀗?쒕떎.",
        descEn: "Buckwheat noodles served in chilled soup made of dongchimi (radish kimchi) liquid and beef broth.",
        descZh: "?①쇋?앭뜙力↑룣黎ㅶ콅?뚨돍?됮쳵黎ㅸ컘?먨넱?뉑광黎곻펽?얍뀯??넖?꾥뜛墉?씊竊뚦냽?졾뀯訝雅쏂맃?쒌곫˘嶺됭즳耀곈뀓??,
        image: "assets/menu/mul_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-53",
        category: "noodle",
        nameKo: "N04. 鍮꾨퉼?됰㈃",
        nameEn: "Bibim Naengmyeon",
        nameZh: "BIBIM NAENGMYEON",
        price: "RM 28.00",
        descKo: "硫붾?濡?留뚮뱺 硫댁쓣 ?띠븘 李щЪ???밴텋 臾쇨린瑜?類 ?ㅼ쓬 ?뚭퀬湲??몄쑁?대굹 ?띿뼱?뚮Т移? 臾? ?ㅼ씠, ?띠? 怨꾨? ?깆쓣 ?밴퀬 怨좎텛???묐뀗?μ뿉 鍮꾨꼈 李④컩寃?癒밸뒗 ?뚯떇?대떎.",
        descEn: "Chilled buckwheat noodles garnished with cold slices of beef, skate, and radish or cucumber. Served with a spicy gochujang mixing sauce.",
        descZh: "?뚦넽?℡쩀鵝욜뵪?욇벧?㏂귟뜛墉?씊??넖?롧뵪?됪객?꿩킋亮뜻꺄亮꿩객?놅펽?뜹릮?얍뀯?썲늾?쏂굢??,
        image: "assets/menu/bibim_naengmyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-54",
        category: "noodle",
        nameKo: "N05. 源移섎퉬鍮붽뎅??,
        nameEn: "Kimchi Bibim Guksu",
        nameZh: "KIMCHI BIBIM GUKSU",
        price: "RM 28.00",
        descKo: "?덉숴?섍쾶 ?듭? 源移섎? ?곗뼱 ?ｊ퀬 怨좎텛?? 李멸린由꾩쑝濡?鍮꾨꼈 ??留ㅼ숴 ?덉숴???쒓뎅 ?꾪넻 鍮꾨퉼援?닔",
        descEn: "Chilled wheat noodles tossed in a sweet, sour, and spicy chili sauce topped with chopped Kimchi.",
        descZh: "?띴빳渦ｆ끝?쒐쉪?겼뇡渦ｆ땶??,
        image: "assets/menu/image_5d08b9_3.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-55",
        category: "noodle",
        nameKo: "N06. 源移섎쭚?닿뎅??,
        nameEn: "Kimchimari Guksu",
        nameZh: "KIMCHIMARI GUKSU",
        price: "RM 28.00",
        descKo: "?숈튂諛뗪뎅?대굹 ?대Т 源移リ뎅 ?먮뒗 源移リ뎅???욎? ?≪닔???띠븘 ??援?닔瑜??ｌ뼱 ?쒖썝?섍쾶 癒밸뒗 ?뚯떇?대떎.",
        descEn: "This is a noodle dish made with chilled dongchimi soup or kimchi soup mixed with beef stock and topped with beef.",
        descZh: "?ⓩ객?앭뜙力↑룣?뽬맃?쒐섀力↑룣?곫끝?쒐춬?꾣광黎곮컘?뚪쳵黎ㅵ쨭?⑨펽?€씉??넖?롦붂?ε넱?뉒쉪遙섉광",
        image: "assets/menu/kimchi_mari_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "noodle-56",
        category: "noodle",
        nameKo: "N07. ?붿튂援?닔",
        nameEn: "Janchi Guksu",
        nameZh: "JANCHI GUKSU",
        price: "RM 28.00",
        descKo: "?띠? 援?닔??怨꾨?吏???깆쑝濡?怨좊챸???밴퀬 硫몄튂?κ뎅??遺?대궦 援?닔濡??덈줈遺???붿튂 ???먮떂????묓븯??????뚯떇?대떎.",
        descEn: "Thin wheat noodles served in a hot, clear anchovy broth with egg, zucchini, and seaweed garnish.",
        descZh: "?①뀸?잏쉪?€씉訝딀붂勇↑썘訝앯춬?쒐쟻竊뚦냽役뉏툓褥浴쇗광黎곮뚧닇?귟눎?ㅷ뵪?ε쑉惹싧??곭뵟?ε??쎾푷若얍???,
        image: "assets/menu/janchi_guksu.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "noodle-57",
        category: "noodle",
        nameKo: "N08. ?쇰㈃",
        nameEn: "Ramyeon",
        nameZh: "RAMYEON",
        price: "RM 23.00",
        descKo: "?묒? ?꾨퉬???볦뿬 ???쇳겙?섍퀬 瑗щ뱾瑗щ뱾???쒓뎅???몄뒪?댄듃 留ㅼ슫 ?쇰㈃ (怨꾨? 諛????≪넚 ?ы븿)",
        descEn: "Spicy and savory Korean instant noodle cooked in a hot brass pot with eggs and green onion.",
        descZh: "腰숃쐽役볣긽?꾦윪凉뤷뜵繇잍뼶堊욘땳??,
        image: "assets/menu/ramyeon.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-58",
        category: "other-cuisine",
        nameKo: "R01. ?뚯넡鍮꾨퉼諛?,
        nameEn: "Dolsot Bibimbap",
        nameZh: "DOLSOT BIBIMBAP",
        price: "RM 30.00",
        descKo: "?④굅???뚯넡??諛κ낵 ?좎꽑???ㅼ깋 ?섎Ъ, 蹂띠? ?뚭퀬湲? 怨꾨? ?몃Ⅸ?먮? ?щ젮 怨좎텛?μ뿉 鍮꾨꼈 癒밸뒗 ?쒖떇 ???鍮꾨퉼諛?,
        descEn: "Bibimbap served in a sizzling hot stone pot. The crispy rice at the bottom, mixed with various toppings and gochujang.",
        descZh: "?ⓨ뒥??쓽?녜봾訝?늽?ユ붂?η교耀?곩릢燁띸킔??and ?믦굢訝앾펽?②쐽濾믧뀻?뽭뀻亦방릣?뚦뜵???,
        image: "assets/menu/dolsot_bibimbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-59",
        category: "other-cuisine",
        nameKo: "R03. ?뚮텋怨좉린蹂띠쓬諛?,
        nameEn: "Beef Bulgogi Bokkeumbap",
        nameZh: "BEEF BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "遺?쒕읇怨?吏?“由꾪븳 ?뚮텋怨좉린? ?쇱콈瑜?諛κ낵 ?④퍡 泥좏뙋?먯꽌 怨좎냼?섍쾶 蹂띠븘???뚮텋怨좉린 蹂띠쓬諛?,
        descEn: "Stir-fried rice with tender, savory beef bulgogi and fresh vegetables.",
        descZh: "腰숁탶?ㅷ돍?됦툗鸚㎫교耀?뭽?ц룣?③뱚?요툓?믣댍?꾤풆?녕깶?됬굮耀?,
        image: "assets/menu/beep_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-60",
        category: "other-cuisine",
        nameKo: "R04. ?쇱?遺덇퀬湲곕낭?뚮갈",
        nameEn: "Dwaeji Bulgogi Bokkeumbap",
        nameZh: "DWAEJI BULGOGI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "留ㅼ숴?ъ숴??怨좎텛???쇱?遺덇퀬湲??뚯뒪濡?諛κ낵 ?쇱콈瑜?留쏆엳寃?遺?留쏅굹寃?蹂띠븘??蹂띠쓬諛?,
        descEn: "Stir-fried rice with sweet and spicy pork bulgogi and assorted vegetables.",
        descZh: "?⒴폀渦ｇ굮?よ굢訝롧교耀?룋縟쒐뼅訝壅루굮?띄쉪遙섉꽏佯?뙦?됬굮耀?,
        image: "assets/menu/dwaeji_bulgogi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-61",
        category: "other-cuisine",
        nameKo: "R05. 源移섎낭?뚮갈",
        nameEn: "Kimchi Bokkeumbap",
        nameZh: "KIMCHI BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "?좉?移섏? 踰좎씠而??먮뒗 怨좉린瑜?蹂띠? ??李멸린由꾩쓣 ?먮Ⅸ 蹂띠쓬諛??꾩뿉 諛붿궘??怨꾨??꾨씪?대? ?뱀? ?붾━",
        descEn: "Kimchi fried rice with meat, topped with a fried egg and seaweed flakes.",
        descZh: "力↑룣?뚨교耀?굮?띰펽亮띌뀓餓η뀕?뗧쉪力↑룣?믧?",
        image: "assets/menu/kimchi_bokkeumbap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "other-cuisine-62",
        category: "other-cuisine",
        nameKo: "R06. ?≪콈蹂띠쓬諛?,
        nameEn: "Japchae Bokkeumbap",
        nameZh: "JAPCHAE BOKKEUMBAP",
        price: "RM 26.00",
        descKo: "?쒖떇 ?붿튂 ?붾━???밸㈃ ?≪콈? 諛μ쓣 ?④퍡 ??遺덉뿉 蹂띠븘??已꾧퉫?섍퀬 怨좎냼???≪콈 蹂띠쓬諛?,
        descEn: "Korean glass noodle (Japchae) and rice pan fried with assorted seasoned vegetables.",
        descZh: "?⒴폀?귟룣竊덄벚???暎됬쾳訝앾펹訝롥릢映삭컘?녘뵮?쒎뭽映녜??뚨굮?꾣쓡?쒐굮耀?,
        image: "assets/menu/japchae_bokkeumbap.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-63",
        category: "other-cuisine",
        nameKo: "R07. 二쇰㉨諛?,
        nameEn: "Jumeokbap",
        nameZh: "JUMEOKBAP",
        price: "RM 20.00",
        descKo: "?곕쑜??諛μ뿉 怨좎냼??李멸린由? ?듦묠, 議곕? 源媛猷⑤? 議곕Ъ議곕Ъ 踰꾨Т???????ш린濡??숆??숆??섍쾶 萸됱튇 二쇰㉨諛?,
        descEn: "Hand-rolled rice balls seasoned with fragrant sesame oil, sesame seeds, and seaweed flakes.",
        descZh: "?뚦뀯役룩땾閻롥뭽?ц룣?뗥램?뤸닇?꾢쐠壤????,
        image: "assets/menu/jumeokbap.jpg",
        badge: "",
        serving: "1-2 Pax",
        spicy: 0
    },
    {
        id: "other-cuisine-64",
        category: "other-cuisine",
        nameKo: "R08. 怨듦린諛?,
        nameEn: "Bap",
        nameZh: "BAP",
        price: "RM 6.00",
        descKo: "留ㅼ옣?먯꽌 留ㅼ씪 ?좎꽑?섍쾶 吏? 怨좎뒳怨좎뒳?섍퀬 李곗쭊 ???諛?怨듦린諛?,
        descEn: "Freshly steamed white sticky rice bowl.",
        descZh: "?썹교耀?,
        image: "assets/menu/bap.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-65",
        category: "dosilak",
        nameKo: "L02. 遺덇퀬湲곕룄?쒕씫",
        nameEn: "Bulgogi Dosilak",
        nameZh: "BULGOGI DOSILAK",
        price: "RM 25.00",
        descKo: "遺덇퀬湲? 諛? 諛섏갔???댁슦?ъ쭊 ?뚯갔 ?뚮텋怨좉린 ?꾩떆??,
        descEn: "Slices of prime beef simmered in its own juices and a special soya sauce broth served in a lunchbox.",
        descZh: "?끻맜?ㅷ돍?됥곭교耀?룋?꾢폀?띹룣?꾦윪凉뤹깶?쏂굢堊욕퐪",
        image: "assets/menu/bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-66",
        category: "dosilak",
        nameKo: "L03. ?쇱?遺덇퀬湲곕룄?쒕씫",
        nameEn: "DejiBulgogi Dosilak",
        nameZh: "DEJIBULGOGI DOSILAK",
        price: "RM 25.00",
        descKo: "留ㅼ숴???쇱?遺덇퀬湲곗? 諛? 諛섏갔???댁슦?ъ쭊 ?꾩떆??,
        descEn: "Pork and assortment of vegetables stir-fried with Korean chili paste served in a lunchbox.",
        descZh: "?끻맜渦ｇ굮?よ굢?곭교耀?룋?꾢폀?띹룣?꾦윪凉뤺쐽?믥뙦?됦씩壤?,
        image: "assets/menu/dwaeji_bulgogi_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-67",
        category: "dosilak",
        nameKo: "L04. ?ㅼ쭠?대낭?뚮룄?쒕씫",
        nameEn: "Ojingeo Bokeum Dosilak",
        nameZh: "OJINGEO BOKEUM DOSILAK",
        price: "RM 25.00",
        descKo: "留ㅼ숴???ㅼ쭠?대낭?뚭낵 諛? 諛섏갔???④퍡 ?ㅼ뼱媛??꾩떆??,
        descEn: "Fried squid in a sauce of Korean chili paste served in a lunchbox.",
        descZh: "?끻맜渦ｇ굮浴욥굴?곭교耀?룋?꾢폀?띹룣?꾦윪凉뤺쐽?믧굻浴쇌씩壤?,
        image: "assets/menu/ojingeo_bokkeum_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "dosilak-68",
        category: "dosilak",
        nameKo: "L05. 蹂댁뙂?꾩떆??,
        nameEn: "Bossam Dosilak",
        nameZh: "BOSSAM DOSILAK",
        price: "RM 25.00",
        descKo: "遺?쒕윭???섏쑁 蹂댁뙂怨?臾대쭚??씠, 諛? 諛섏갔???댁슦?ъ쭊 ?꾩떆??,
        descEn: "Special recipe steamed tender pork belly served in a lunchbox with side dishes.",
        descZh: "?끻맜?밧댍燁섉뼶歷낁뮯饔?ォ?썲늾?됥곭교耀?룋?꾢폀?띹룣?꾦윪凉뤹쇋?뉓굢堊욕퐪",
        image: "assets/menu/bossam_dosilak.png",
        badge: "",
        serving: "1 Pax",
        spicy: 0
    },
    {
        id: "dosilak-69",
        category: "dosilak",
        nameKo: "L07. 源移섎낭?뚮룄?쒕씫",
        nameEn: "Kimchi Bokkeum Dosilak",
        nameZh: "KIMCHI BOKKEUM DOSILAK",
        price: "RM 25.00",
        descKo: "留ㅼ숴?섍쾶 蹂띠븘???쇨껸??源移섎낭?뚭낵 諛? 諛섏갔???댁슦?ъ쭊 ?꾩떆??,
        descEn: "Belly pork fried with Kimchi served in a lunchbox with side dishes.",
        descZh: "?끻맜力↑룣?믢틪?김굢?곭교耀?룋?꾢폀?띹룣?꾦윪凉뤸끝?쒐굮?됦씩壤?,
        image: "assets/menu/kimchi_bokkeum_dosilak.jpg",
        badge: "",
        serving: "1 Pax",
        spicy: 1
    },
    {
        id: "beverage-70",
        category: "beverage",
        nameKo: "V01. Coke",
        nameEn: "Coke",
        nameZh: "COKE",
        price: "RM 5.00",
        descKo: "肄붿뭅肄쒕씪 ?꾩궛?뚮즺 (罹?",
        descEn: "CocaCola Soda Drink (Can)",
        descZh: "營먫즳??룭??퉸閻녜끂耀?뼑",
        image: "assets/menu/coke.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-71",
        category: "beverage",
        nameKo: "V02. Sprite",
        nameEn: "Sprite",
        nameZh: "SPRITE",
        price: "RM 5.00",
        descKo: "?ㅽ봽?쇱씠???꾩궛?뚮즺 (罹?",
        descEn: "Sprite Soda Drink (Can)",
        descZh: "營먫즳?ょˇ閻녜끂耀?뼑",
        image: "assets/menu/sprite.png",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-72",
        category: "beverage",
        nameKo: "V03. 100 Plus",
        nameEn: "100 Plus",
        nameZh: "100 PLUS",
        price: "RM 5.00",
        descKo: "諛깊뵆?ъ뒪 ?댁삩?뚮즺 (罹?",
        descEn: "100 Plus Isotonic Drink (Can)",
        descZh: "營먫즳100 Plus嶺됪툠獵삣춴耀?뼑",
        image: "assets/menu/100_plus.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-73",
        category: "beverage",
        nameKo: "V04. Galamanddeunbae",
        nameEn: "Galamanddeunbae",
        nameZh: "GALAMANDDEUNBAE",
        price: "RM 7.00",
        descKo: "援?궛 ?댄깭 媛덉븘留뚮뱺 諛??쒖썝???뚮즺 (罹?",
        descEn: "Korean Crushed Pear Juice (Can)",
        descZh: "營먫즳?⒴쎖役룟ㄺ閻롦˘黎?,
        image: "assets/menu/galamanddeunbae.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-74",
        category: "beverage",
        nameKo: "V05. ?뚯＜",
        nameEn: "Soju",
        nameZh: "SOJU",
        price: "RM 35.00",
        descKo: "?쒓뎅 ?꾪넻 ?뚯＜ 二쇰쪟",
        descEn: "Traditional Korean Liquor (Soju)",
        descZh: "?⒴쎖鴉좂퍨?㏝뀙",
        image: "assets/menu/soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-75",
        category: "beverage",
        nameKo: "V08. ?덈が?뚯＜",
        nameEn: "Lemon Soju",
        nameZh: "LEMON SOJU",
        price: "RM 38.00",
        descKo: "?곹겮???덈が??釉붾젋?⑺븳 ?곸풄??怨쇱씪 ?뚯＜",
        descEn: "Korean Liquor with Lemon",
        descZh: "?졿が繇롥뫑?㏝뀙",
        image: "assets/menu/lemon_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-76",
        category: "beverage",
        nameKo: "V09. ?ㅼ씠?뚯＜",
        nameEn: "Cucumber Soju",
        nameZh: "CUCUMBER SOJU",
        price: "RM 38.00",
        descKo: "?쒖썝?섍퀬 源붾걫??留쏆쓣 ?먮옉?섎뒗 ?섏젣 ?ㅼ씠 ?뚯＜",
        descEn: "Korean Liquor infused with fresh Cucumber slices",
        descZh: "容꾤뱶繇롥뫑?㏝뀙",
        image: "assets/menu/cucumber_soju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-77",
        category: "beverage",
        nameKo: "V10. ??닿굅罹붾㎘二?,
        nameEn: "Tiger Beer (Can)",
        nameZh: "TIGER BEER (CAN)",
        price: "RM 13.00",
        descKo: "泥?웾媛먯씠 ?섏튂???섏엯 ??닿굅 罹붾㎘二?,
        descEn: "Tiger Beer (Can)",
        descZh: "營먫즳?롧뎹?ㅹ뀙",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Can",
        spicy: 0
    },
    {
        id: "beverage-78",
        category: "beverage",
        nameKo: "V11. ??닿굅蹂묐㎘二?,
        nameEn: "Tiger Beer (Bottle)",
        nameZh: "TIGER BEER (BOTTLE)",
        price: "RM 30.00",
        descKo: "?쒖썝?섍퀬 ?띾?媛 ?댁븘?덈뒗 ?ㅻ━吏????닿굅 蹂묐㎘二?,
        descEn: "Tiger Beer (Bottle)",
        descZh: "?띈즳?롧뎹?ㅹ뀙",
        image: "assets/menu/tiger_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-79",
        category: "beverage",
        nameKo: "V12. ?쒓뎅蹂묐㎘二?,
        nameEn: "Korean Beer",
        nameZh: "KOREAN BEER",
        price: "RM 35.00",
        descKo: "?쒓뎅 ?꾪넻 ?쇨굅 蹂묐㎘二?(移댁뒪 ?먮뒗 ?뚮씪)",
        descEn: "Korean Beer (Bottle, e.g. Cass or Terra)",
        descZh: "?띈즳?⒴쎖?ㅹ뀙竊뉱ass/Terra竊?,
        image: "assets/menu/korean_beer.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-80",
        category: "beverage",
        nameKo: "V13. ?ㅼ떗?몄＜",
        nameEn: "OShipSaeJu",
        nameZh: "OSHIPSaeJu",
        price: "RM 90.00",
        descKo: "?뚯＜? 諛깆꽭二쇰? ?⑷툑 鍮꾩쑉濡??욎뼱 李④컩寃?利먭린???쒓뎅 ?뱀젣 誘뱀뒪 ?쎌＜",
        descEn: "Combination of Soju & BaekSaeJu in an ice chilled bottle.",
        descZh: "?곈븛?띈즳雅붷뛻略곲뀙竊덄깾?믢툗?얍쾪?믥쉪容꾦뇫驪붶풃瘟껃뭽?믭펹",
        image: "assets/menu/oshipsaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-81",
        category: "beverage",
        nameKo: "V14. 諛깆꽭二?,
        nameEn: "BaekSaeJu",
        nameZh: "BAEKSAEJU",
        price: "RM 60.00",
        descKo: "12媛吏 ?쒖빟?щ? ?ｌ뼱 鍮싳? 源딆? 留쏆쓽 ?쒓뎅 ?꾪넻 ?쒕갑 ?쎌＜",
        descEn: "Korean Herbal Liquor brewed with 12 organic herbs.",
        descZh: "?얍쾪?믭펷?띶릦?곦틠燁띹뜆?ц뜱?먬끏?띄쉪鴉좂퍨?⒴쎖?사뵟?믭펹",
        image: "assets/menu/baeksaeju.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-82",
        category: "beverage",
        nameKo: "V15. ?ㅼ쨷留?,
        nameEn: "SeolJungMae",
        nameZh: "SEOLJUNGMAE",
        price: "RM 65.00",
        descKo: "?좎꽑??留ㅼ떎???듭㎏濡?移⑥텧?쒖폒 ?ъ숴?섍퀬 ?곹겮???꾨━誘몄뾼 留ㅼ떎二?,
        descEn: "Korean Plum Wine featuring real green plums in the bottle.",
        descZh: "?や릎歟낉펷?뉒뵪鴉섋뇽?믤쥌?욕댍?꾦윪?썽쳵瀛㎪쥌耶먬뀙竊?,
        image: "assets/menu/seoljungmae.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    },
    {
        id: "beverage-83",
        category: "beverage",
        nameKo: "V16. 蹂듬텇??,
        nameEn: "BokBunJa",
        nameZh: "BOKBUNJA",
        price: "RM 65.00",
        descKo: "?ъ숴?섍퀬 ?レ?留쏆쓽 洹좏삎??議고솕濡쒖슫 嫄닿컯 ?앸Ъ??蹂듬텇?먯＜",
        descEn: "Korean Raspberry Wine known for its sweet, rich berry flavor and health benefits.",
        descZh: "誤녺썓耶먬뀙竊덆뇞?ⓧ폍兀②쫮?녶춴?욕댍?꾤뵖?쒒윪?썼쫮?녶춴?믭펹",
        image: "assets/menu/bokbunja.jpg",
        badge: "",
        serving: "1 Bottle",
        spicy: 0
    }
];
